### PR TITLE
feat(database): database hover animation

### PR DESCRIPTION
**Pull request by AyushAgrawal-A2**
Closes: #4972 

Changes:
- Added hover animation on the mentioned elements in database block.

### CODE REVIEW

**Comment by AyushAgrawal-A2** [comment]
Waiting to reply to https://github.com/toeverything/blocksuite/issues/4972#issuecomment-1811964690 before submitting for review.

**Review by doodlewind — COMMENTED** [review]
Thanks for the improvement! Just want to know if the following 2 places could support the hovering animation together?

https://github.com/toeverything/blocksuite/assets/7312949/24e4d919-a4f4-4bf0-aeb1-33786fb20c4d

**Comment by AyushAgrawal-A2** [comment]
> Thanks for the improvement! Just want to know if the following 2 places could support the hovering animation together?
> 
>  Screen.Recording.2023-11-16.at.08.11.32.mov

As these two elements are part of different parent elements, I can think of two ways of doing this:
1. Using js, add eventlistener for hover on both and then add class to all linked components.
2. Using css :has() selector. This is a new selector and not present in current release of firefox. It is available on firefox 120 nightly build though. (ref: https://stackoverflow.com/questions/76133179/cross-browser-alternative-to-css-has-pseudo-class). As affine using chromium under the hood, this should work for our use case.

Screencast using css :has() selector on chrome.

https://github.com/toeverything/blocksuite/assets/54364088/11a621ad-042b-4c58-9455-389624114faf

Also, please clarify if 
1. only hover state is to be linked b/w `+` svg and `Add` button, or
2. same animation `150ms (0.42, 0, 1, 1)` also needs to be added to background color change on hover.

currently background changes on hover with no animation. I am confused because of the term `hovering animation together`

**Comment by doodlewind** [comment]
The effect looks great! Using `has` should be adequate since it's a styling enhancement, and let's make the animation added on background color change :D

**Review by doodlewind — APPROVED** [review]
Your work is impressive! If you are looking for GitHub sponsor, feel free to DM me at doodlewind@toeverything.info :D

**Pull request merged**
