### PR TITLE
fix: edgeless root service undefined

### PR DESCRIPTION
**Pull request by akumatus**
Temporary method to fix edgeless root service undefined issue.

### CODE REVIEW

**Comment by akumatus** [comment]
* **#7854** <a href="https://app.graphite.dev/github/pr/toeverything/blocksuite/7854?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @akumatus and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by doouding — COMMENTED** [review]
This might be fixed after #7853 .

**Comment by akumatus** [comment]
> This might be fixed after #7853 .

Why make this change? Is it a bug in signal?

**Comment by doouding** [comment]
> > This might be fixed after #7853 .
> 
> Why make this change? Is it a bug in signal?

Yes, the official lit signal integration may cause a memory leak. It may execute `render`, `connectedCallback`, `firstUpdated`, etc., even after the element has disconnected.

**Pull request closed without merging**
