### PR TITLE
chore(editor): add option to prevent auto focus

### LINKED ISSUE #1849: Unexpected auto focus behavior
To reproduce, open https://blocksuite-docs.vercel.app/getting-started.html with a small page height:

https://user-images.githubusercontent.com/7312949/227486291-d957efa7-4f73-49c9-b518-41a2d5f09dc3.mov

Autofocus leads to page jump on init, and may be problematic if we have multiple editor instances to co-exist. @lawvs can we make this configurable?

### PR DESCRIPTION
**Pull request by Flrande**
Close #1849

### CODE REVIEW

**Review by lawvs — CHANGES_REQUESTED** [review]
It's a workaround, and seem not work

https://user-images.githubusercontent.com/18554747/227499238-abb884b3-fa9b-4064-a2da-356a579f6b86.mov

**Review by himself65 — APPROVED** [review]

**Comment by himself65** [comment]
is there any way to test it?

**Review by doodlewind — APPROVED** [review]

**Comment by doodlewind** [comment]
> is there any way to test it?

See #1849

**Comment by himself65** [comment]
> > is there any way to test it?
> 
> See #1849

I mean in e2e test

**Pull request closed without merging**
