### PR TITLE
fix(page): shift + arrow text selection

### PR DESCRIPTION
**Pull request by AyushAgrawal-A2**
Closes: #2684 
Closes: #4435 
Closes: #1290

Changes:
- Text Selection: Implemented app logic for changing text selection using arrow keys inside the note block.
- Reverse Text Selection: If text selction has been made using mouse and user continues to modify the selection using keyboard, the selection should change from the last cursor position. For this to work for reverse text selection (right to left / bottom to top) I had to modify:
   - `_mergeRanges` to calculate if reverse selection is made.
   - `_renderRange` to render reverse selection correctly.
   - add `isReverse` property to `TextSelection` to store reverse selection state and calculate the start / end of selection.
- Format Bar: Format bar appears on text selection and hide the text, blocking it from caret position calculation. To prevent this I opted to hide all widgets before caret position calculation and then restore them to their original state.

https://github.com/toeverything/blocksuite/assets/54364088/ef57f25d-3f23-49cd-8f48-6d8bb9847584

### CODE REVIEW

**Comment by Saul-Mirone** [comment]
Great work! However, I think it won't work for multiple notes in doc mode?

**Comment by doodlewind** [comment]
> Great work! However, I think it won't work for multiple notes in doc mode?

No worries, I'd say that could be an edge case for further PRs.

**Comment by AyushAgrawal-A2** [comment]
> Great work! However, I think it won't work for multiple notes in doc mode?

Currently it works within one note only. It can be extended for multi note as well. I have made a lot of changes here. Can I add that in another PR ?

**Comment by Saul-Mirone** [comment]
> > Great work! However, I think it won't work for multiple notes in doc mode?
> 
> Currently it works within one note only. It can be extended for multi note as well. I have made a lot of changes here. Can I add that in another PR ?

Sure.

**Review by Saul-Mirone — APPROVED** [review]

**Pull request merged**
