### PR TITLE
feat: support del and underline format for markdown export 

### LINKED ISSUE #646: Missing underline and strikethrough style in exported markdown
The exported markdown doesn't contain the underline and strikethrough styles, but the bold and italics styles can be correctly exported.

image

### PR DESCRIPTION
**Pull request by AkaraChen**
Fix #646

### CODE REVIEW

**Review by himself65 — COMMENTED** [review]
Could you please add a test

**Comment by AkaraChen** [comment]
Sorry, I haven't learned playwright and I don't know how to write tests.

**Comment by himself65** [comment]
it's fine. I will test this manually and merge this

**Comment by himself65** [comment]
blocking as I think there're some bugs. need to investigate

**Review by doodlewind — APPROVED** [review]
Current one-liner fix looks good, let's land this one, thanks!

**Pull request merged**
