### PR TITLE
fix: click bottom should add a new paragraph block

### LINKED ISSUE #726: Click bottom should add a new paragraph block
https://user-images.githubusercontent.com/14026360/212597151-e0a675cf-990a-45ac-a47c-662c99781fd9.mov

Preview: https://blocksuite-toeverything.vercel.app/?init=AAMAAxEHx4vDxR%2BvAaABAAIBAAgBBRIBAQoBAEQOAQFqMAgBAgpMjgEBAwxOlAEBAwxOiAEBAwyMAgIWAvQCmAMBAgpMlAEBAgqaAQIKAvQBigkBAgqgAgISAooBAhIC4gS%2BBQECCpgCAgoCtAQCDAL2B4gIAQIKqgUCOgL0BroJAQIKgAMCjAEC3ASWBgECCj4CIgLWMaIxAQIOAQIKXB4KAQFIEAQCREwYAQJEEAU8nDEOAMkCJwAHACgAIQAoACcAKAcnACgBJwAoACcAKAEnAAgAJwAoAScAKACoAAgAJwAoAScAKAAnAAQAiAAnACgBJwAoAScABACIACcAKAEnACgBJwAEAIgAJwAoAScAKAEnAAQAhgCEAIYAhACIACcAKAEnACgAJwAEAIgAJwAoAScAKAAnAAQAhgCEAIYAhACIACcAKAEnACgAJwAEAIYAhACGAIQAhgCEAIYAhACIACcAKAEnACgAJwAEAIYAhACGAIQAhgCEAIYAhACIACcAKAEnACgAJwAEAIYAhACGAIQAiAAnACgBJwAoACcABACGAIQAhgCEAIgAJwAoAScAKAAnAAQAhgCEAIYAhACoAEgAJwAoAScAKAAnAEgAJwAoAScAKAAnAAQAqACEAEgAJwAoAScBqAAGAIQAhgCoAMgAJwAoAScAKAAnAKiFGbwXc3BhY2U6bWV0YXBhZ2VzaWR0aXRsZWNyZWF0ZURhdGVzcGFjZTptZXRhdmVyc2lvbnNhZmZpbmU6cGFyYWdyYXBoYWZmaW5lOnBhZ2VhZmZpbmU6bGlzdGFmZmluZTpmcmFtZWFmZmluZTpjb2RlYWZmaW5lOmRpdmlkZXJhZmZpbmU6ZW1iZWRhZmZpbmU6c3VyZmFjZXNwYWNlOnBhZ2UwNDIzMzY1MDg4Nzowc3lzOmlkc3lzOmZsYXZvdXJzeXM6Y2hpbGRyZW5wcm9wOnRpdGxlc3BhY2U6cGFnZTA0MjMzNjUwODg3OjFzeXM6aWRzeXM6Zmxhdm91cnN5czpjaGlsZHJlbnNwYWNlOnBhZ2UwNDIzMzY1MDg4Nzoyc3lzOmlkc3lzOmZsYXZvdXJzeXM6Y2hpbGRyZW5wcm9wOnh5d2hzcGFjZTpwYWdlMDQyMzM2NTA4ODc6M3N5czppZHN5czpmbGF2b3Vyc3lzOmNoaWxkcmVucHJvcDp0eXBlcHJvcDp0ZXh0VGhpcyBwbGF5Z3JvdW5kIGlzIGRlc2lnbmVkIHRvOnNwYWNlOnBhZ2UwNDIzMzY1MDg4Nzo0c3lzOmlkc3lzOmZsYXZvdXJzeXM6Y2hpbGRyZW5wcm9wOnR5cGVwcm9wOmNoZWNrZWRwcm9wOnRleHTwn5OdIFRlc3QgYmFzaWMgZWRpdGluZyBleHBlcmllbmNlLnNwYWNlOnBhZ2UwNDIzMzY1MDg4Nzo1c3lzOmlkc3lzOmZsYXZvdXJzeXM6Y2hpbGRyZW5wcm9wOnR5cGVwcm9wOmNoZWNrZWRwcm9wOnRleHTimpnvuI8gU2VydmUgYXMgRTJFIHRlc3QgZW50cnkuc3BhY2U6cGFnZTA0MjMzNjUwODg3OjZzeXM6aWRzeXM6Zmxhdm91cnN5czpjaGlsZHJlbnByb3A6dHlwZXByb3A6Y2hlY2tlZHByb3A6dGV4dPCflJcgRGVtb25zdHJhdGUgaG93IEJsb2NrU3VpdGUgcmVjb25jaWxlcyByZWFsLXRpbWUgY29sbGFib3JhdGlvbiB3aXRoIGxpbmtsb2NhbC1maXJzdGxpbmsgZGF0YSBvd25lcnNoaXAuc3BhY2U6cGFnZTA0MjMzNjUwODg3OjdzeXM6aWRzeXM6Zmxhdm91cnN5czpjaGlsZHJlbnByb3A6dHlwZXByb3A6dGV4dENvbnRyb2xsaW5nIFBsYXlncm91bmQgRGF0YSBTb3VyY2VzcGFjZTpwYWdlMDQyMzM2NTA4ODc6OHN5czppZHN5czpmbGF2b3Vyc3lzOmNoaWxkcmVucHJvcDp0eXBlcHJvcDp0ZXh0WW91IG1pZ2h0IGluaXRpYWxseSBlbnRlciB0aGlzIHBhZ2Ugd2l0aCB0aGUgY29kZT9pbml0Y29kZSBVUkwgcGFyYW0uIFRoaXMgaXMgdGhlIGRlZmF1bHQgKG9wdC1pbikgc2V0dXAgdGhhdCBhdXRvbWF0aWNhbGx5IGxvYWRzIHRoaXMgYnVpbHQtaW4gYXJ0aWNsZS4gTWVhbndoaWxlLCB5b3UnbGwgY29ubmVjdCB0byBhIHJhbmRvbSBzaW5nbGUtdXNlciByb29tIHZpYSBhIFdlYlJUQyBwcm92aWRlciBieSBkZWZhdWx0LiBUaGlzIGlzIHRoZSDigJxzaW5nbGUtdXNlciBtb2Rl4oCcIGZvciBsb2NhbCB0ZXN0aW5nLnNwYWNlOnBhZ2UwNDIzMzY1MDg4Nzo5c3lzOmlkc3lzOmZsYXZvdXJzeXM6Y2hpbGRyZW5wcm9wOnR5cGVwcm9wOnRleHRUbyB0ZXN0IHJlYWwtdGltZSBjb2xsYWJvcmF0aW9uLCB5b3UgY2FuIHNwZWNpZnkgdGhlIHJvb20gdG8gam9pbiBieSBhZGRpbmcgdGhlIGNvZGU%2Fcm9vbT1mb29jb2RlIGNvbmZpZyAtIFRyeSBvcGVuaW5nIHRoaXMgcGFnZSB3aXRoIGNvZGU%2Fcm9vbT1mb29jb2RlIGluIHR3byBkaWZmZXJlbnQgdGFicyBhbmQgc2VlIHdoYXQgaGFwcGVucyFzcGFjZTpwYWdlMDQyMzM2NTA4ODc6MTBzeXM6aWRzeXM6Zmxhdm91cnN5czpjaGlsZHJlbnByb3A6dHlwZXByb3A6dGV4dE5vdGUgdGhhdCB0aGUgc2Vjb25kIGFuZCBzdWJzZXF1ZW50IHVzZXJzIHNob3VsZCBub3Qgb3BlbiB0aGUgcGFnZSB3aXRoIHRoZSBjb2RlP2luaXRjb2RlIHBhcmFtIGluIHRoaXMgY2FzZS4gQWxzbywgZHVlIHRvIHRoZSBQMlAgbmF0dXJlIG9mIFdlYlJUQywgYXMgbG9uZyBhcyB0aGVyZSBpcyBhdCBsZWFzdCBvbmUgdXNlciBjb25uZWN0ZWQgdG8gdGhlIHJvb20sIHRoZSBjb250ZW50IGluc2lkZSB0aGUgcm9vbSB3aWxsIGJvbGRhbHdheXNib2xkIGV4aXN0LnNwYWNlOnBhZ2UwNDIzMzY1MDg4NzoxMXN5czppZHN5czpmbGF2b3Vyc3lzOmNoaWxkcmVucHJvcDp0eXBlcHJvcDp0ZXh0SWYgeW91IGFyZSB0aGUgb25seSB1c2VyIGluIHRoZSByb29tLCB5b3VyIGNvbnRlbnQgd2lsbCBiZSBsb3N0IGFmdGVyIHJlZnJlc2guIFRoaXMgaXMgZ3JlYXQgZm9yIGxvY2FsIGRlYnVnZ2luZy4gQnV0IGlmIHlvdSB3YW50IGxvY2FsIHBlcnNpc3RlbmNlLCB5b3UgY2FuIG9wZW4gdGhpcyBwYWdlIHdpdGggdGhlIGNvZGU%2FcHJvdmlkZXJzPWluZGV4ZWRkYiZyb29tPWZvb2NvZGUgY29uZmlnLCB0aGVuIGNsaWNrIHRoZSBpbml0IGJ1dHRvbiBpbiB0aGUgYm90dG9tLWxlZnQgY29ybmVyIHRvIGluaXRpYWxpemUgdGhpcyBkZWZhdWx0IGNvbnRlbnQuc3BhY2U6cGFnZTA0MjMzNjUwODg3OjEyc3lzOmlkc3lzOmZsYXZvdXJzeXM6Y2hpbGRyZW5wcm9wOnR5cGVwcm9wOnRleHRBcyBhIHBybyB0aXAsIHlvdSBjYW4gY29tYmluZSBtdWx0aXBsZSBwcm92aWRlcnMhIEZvciBleGFtcGxlLCBmZWVsIGZyZWUgdG8gb3BlbiB0aGlzIHBhZ2Ugd2l0aCBjb2RlP3Byb3ZpZGVycz1pbmRleGVkZGIsd2VicnRjJnJvb209aGVsbG9jb2RlIHBhcmFtcywgYW5kIHNlZSBpZiBldmVyeXRoaW5nIHdvcmtzIGFzIGV4cGVjdGVkLiBIYXZlIGZ1biFzcGFjZTpwYWdlMDQyMzM2NTA4ODc6MTNzeXM6aWRzeXM6Zmxhdm91cnN5czpjaGlsZHJlbnByb3A6dHlwZXByb3A6dGV4dEZvciBhbnkgZmVlZGJhY2ssIHBsZWFzZSB2aXNpdCBsaW5rQmxvY2tTdWl0ZSBpc3N1ZXNsaW5rIPCfk41zcGFjZTpwYWdlMDQyMzM2NTA4ODc6MTRzeXM6aWRzeXM6Zmxhdm91cnN5czpjaGlsZHJlbnByb3A6dHlwZXByb3A6dGV4dHNwYWNlOnBhZ2UwNDIzMzY1MDg4NzoxNXN5czppZHN5czpmbGF2b3Vyc3lzOmNoaWxkcmVucHJvcDp0eXBlcHJvcDp0ZXh0YGBgc3BhY2U6cGFnZTA0MjMzNjUwODg3OjE2c3lzOmlkc3lzOmZsYXZvdXJzeXM6Y2hpbGRyZW5wcm9wOnRleHRjb2RlLWJsb2NrCmNvZGUtYmxvY2tzcGFjZTpwYWdlMDQyMzM2NTA4ODc6MTdzeXM6aWRzeXM6Zmxhdm91cnN5czpjaGlsZHJlbnByb3A6dHlwZXByb3A6dGV4dAoFAgVKAAgQSwAMCw4MDgsMBgsMCgsMBgsMCwwGCwwJCwwGCwxJAB8LDAYLDAkMCSELDAYLDAkMCRsLDAYLDAkMCYYBBAsEEAsMBgsMSQAiCwwGCwxJAC0EBQSpAwsMBgsMSQCQAQQJBCUECQQsCw0GCwxJAIwBBAUEmgIEBgQHCw0GCwxJALUCBB0EoQELDQYLDEkAoAEEJgQ7Cw0GCwxJAB8EEQQDCw0GCwxJAAsNBgsMSQABAgsNBgsMCQoBCgsNBgsMSQBPAQAAAwEAAAcBAAADAQAAAwEAAAQBAAAFAQAABgEAAAYBAAAGAQAABQEAAAUBAAAFAQAABQEAAAUBAAAFAQAABQEAAAQBAAAFAQAABAEAADUAQQEAAQABAAEAAgEAAgEAAgEAAgEAAgEAAgEAAgEAAgEAAgEAAgEAAgEAAgEAAgEAAgEAAgJBVwHDAQB3BXBhZ2Uwe0J4W4xObJAAfQF9AX0BfQF9AX0BfQF9AXcMNDIzMzY1MDg4NzowdwthZmZpbmU6cGFnZXcgV2VsY29tZSB0byBCbG9ja1N1aXRlIHBsYXlncm91bmR3DDQyMzM2NTA4ODc6MXcOYWZmaW5lOnN1cmZhY2V3DDQyMzM2NTA4ODc6MncMNDIzMzY1MDg4NzoydwxhZmZpbmU6ZnJhbWV3DVswLDAsNzIwLDQ4MF13IFdlbGNvbWUgdG8gQmxvY2tTdWl0ZSBwbGF5Z3JvdW5kdww0MjMzNjUwODg3OjN3DDQyMzM2NTA4ODc6M3cQYWZmaW5lOnBhcmFncmFwaHcEdGV4dHcMNDIzMzY1MDg4Nzo0dww0MjMzNjUwODg3OjR3C2FmZmluZTpsaXN0dwhidWxsZXRlZHl3DDQyMzM2NTA4ODc6NXcMNDIzMzY1MDg4Nzo1dwthZmZpbmU6bGlzdHcIYnVsbGV0ZWR5dww0MjMzNjUwODg3OjZ3DDQyMzM2NTA4ODc6NncLYWZmaW5lOmxpc3R3CGJ1bGxldGVkeXczaHR0cHM6Ly9tYXJ0aW4ua2xlcHBtYW5uLmNvbS9wYXBlcnMvbG9jYWwtZmlyc3QucGRmfncMNDIzMzY1MDg4Nzo3dww0MjMzNjUwODg3Ojd3EGFmZmluZTpwYXJhZ3JhcGh3Amgydww0MjMzNjUwODg3Ojh3DDQyMzM2NTA4ODc6OHcQYWZmaW5lOnBhcmFncmFwaHcEdGV4dHh%2Bdww0MjMzNjUwODg3Ojl3DDQyMzM2NTA4ODc6OXcQYWZmaW5lOnBhcmFncmFwaHcEdGV4dHh%2BeH53DTQyMzM2NTA4ODc6MTB3DTQyMzM2NTA4ODc6MTB3EGFmZmluZTpwYXJhZ3JhcGh3BXF1b3RleH54fncNNDIzMzY1MDg4NzoxMXcNNDIzMzY1MDg4NzoxMXcQYWZmaW5lOnBhcmFncmFwaHcEdGV4dHh%2Bdw00MjMzNjUwODg3OjEydw00MjMzNjUwODg3OjEydxBhZmZpbmU6cGFyYWdyYXBodwR0ZXh0eH53DTQyMzM2NTA4ODc6MTN3DTQyMzM2NTA4ODc6MTN3EGFmZmluZTpwYXJhZ3JhcGh3BHRleHR3MWh0dHBzOi8vZ2l0aHViLmNvbS90b2V2ZXJ5dGhpbmcvYmxvY2tzdWl0ZS9pc3N1ZXN%2Bdw1bMCwwLDcyMCw4MzFddw00MjMzNjUwODg3OjE0dw00MjMzNjUwODg3OjE0dxBhZmZpbmU6cGFyYWdyYXBodwR0ZXh0dw00MjMzNjUwODg3OjE1dw00MjMzNjUwODg3OjE1dxBhZmZpbmU6cGFyYWdyYXBodwR0ZXh0dwxbMCwwLDcyMCwzMl13DTQyMzM2NTA4ODc6MTZ3DTQyMzM2NTA4ODc6MTZ3C2FmZmluZTpjb2RldwxbMCwwLDcyMCwyNl14fncNWzAsMCw3MjAsMTE0XXcNNDIzMzY1MDg4NzoxN3cNNDIzMzY1MDg4NzoxN3cQYWZmaW5lOnBhcmFncmFwaHcEdGV4dHcNWzAsMCw3MjAsMTM0XXcMWzAsMCw3MjAsOTRdAcfF4eIPBQMAGAABvwwGAAMI

### PR DESCRIPTION
**Pull request by himself65**
Fixes: https://github.com/toeverything/blocksuite/issues/726

### CODE REVIEW

**Comment by himself65** [comment]
My local test suite is broken. adding test in the future

**Comment by lawvs** [comment]
In livedemo, If the last block is a paragraph and is empty, the text block will be focused.

**Comment by himself65** [comment]
> 

But in our case, what if image/code/database block is last one

**Comment by himself65** [comment]
And I think in live demo, they do add a new group block

**Pull request merged**
