### PR TITLE
fix(blocks): refine element toolbar ui

### PR DESCRIPTION
**Pull request by fundon**
Closes: [AFF-1084](https://linear.app/affine-design/issue/AFF-1084/在-element-toolbar-上的-button-padding-没有统一)

### CODE REVIEW

**Comment by fundon** [comment]
* **#7064** <a href="https://app.graphite.dev/github/pr/toeverything/blocksuite/7064?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @fundon and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Flrande — APPROVED** [review]
LGTM, but I suggest letting the UI side do a double check and link this PR to #7059

**Comment by fundon** [comment]
@Svaney-ssman @hwangdev97 Please review it.

**Comment by Svaney-ssman** [comment]
Here are the remaining UI issues: @fundon 
1. Canvas text: dividers have not yet been unified.
image

2. shape: need to combine border style and color button
image

3. shape with text: dividers have not yet been unified.
image

4. connector： need to combine border style and color button
image

5. note: dropdown icon color incorrect
image

**Comment by fundon** [comment]
> The only issue is all the dividers and borders should be 0.5px wide, others all look good to me👍🏻

Check the border and dropdown menu. Thanks.

**Review by Svaney-ssman — APPROVED** [review]
GOOOD

**Pull request merged**
