### PR TITLE
refactor(blocks): editor-toolbar component

### PR DESCRIPTION
**Pull request by fundon**
Closes: [BS-702](https://linear.app/affine-design/issue/BS-702/重构-toolbar，组件复用)

### `editor-toolbar`

This is a generic toolbar component that can be used in different modes.

Scenarios:
* inline
* block
* element

Includes components: 
* `editor-toolbar`
* `editor-icon-button`
* `editor-menu-button`
* `editor-menu-content`
* `editor-menu-action`
* `editor-toolbar-separator`

These duplicate components will be removed in the following PRs:
See  `packages/blocks/src/root-block/edgeless/components/buttons`.

### CODE REVIEW

**Comment by fundon** [comment]
* **#7475** <a href="https://app.graphite.dev/github/pr/toeverything/blocksuite/7475?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @fundon and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by Saul-Mirone** [comment]
You should remove the duplicate components in this graphite stack.

**Comment by fundon** [comment]
The next PR will include it in stack. But there are many files to change. Step by step.

**Comment by fundon** [comment]
> 1. The base direction is to avoid more `<affine-xxx>` components since for common components, they should be moving towards reusable components that are not specific to Affine. So I'd suggest making the naming `<editor-toolbar>`, `<editor-toolbar-separator>`, `<editor-menu-xxx>`.

Good idea. Make sense.



> 2. Are these components now ready to be reused in doc editor? If not, keeping the `<edgeless-xxx>` naming may make more sense.

Sure, they should all be common components.

**Review by Saul-Mirone — APPROVED** [review]
LGTM

**Review by doodlewind — APPROVED** [review]

**Pull request merged**
