### PR TITLE
fix: onShowSearch alter the searchState

### PR DESCRIPTION
**Pull request by luke358**
https://user-images.githubusercontent.com/48149577/232205825-93383109-a44e-44bb-965a-1d95eacd328c.mov

### CODE REVIEW

**Comment by luke358** [comment]
The main cause of this issue is likely the modification of the searchState. When in the Searching or SearchInput state, the searchInput is open and should not be triggered repeatedly. Furthermore, repeated triggering can result in the duplication of the onClickOutside event registration.

_searchInput to  _searchContainer: related: #2066. It seems that some conflicts have been overwritten.

**Comment by zqran** [comment]
> The main cause of this issue is likely the modification of the searchState. When in the Searching or SearchInput state, the searchInput is open and should not be triggered repeatedly. Furthermore, repeated triggering can result in the duplication of the onClickOutside event registration.
> 
> _searchInput to _searchContainer: related: #2066. It seems that some conflicts have been overwritten.

Thanks for your feedback, I'm reviewing your changes. Now, after showing the search box, clicking the search icon again should do noting. I will change it.

**Comment by zqran** [comment]
Since `Database` is still under development, some interaction details still need to be confirmed, so we may modify your code implementation. Alternatively, you can open an issue with your suggestions.

Anyway, thanks a lot for your contribution!

**Review by zqran — APPROVED** [review]

**Comment by luke358** [comment]
> Since `Database` is still under development, some interaction details still need to be confirmed, so we may modify your code implementation. Alternatively, you can open an issue with your suggestions.
> 
> Anyway, thanks a lot for your contribution!

yeah，it's ok.

**Review by doodlewind — APPROVED** [review]
Thanks for your help improving database block! FYI, feel free to join our discussion group at https://t.me/AffineDevCN if you are a Chinese speaker 😀

**Pull request merged**
