### PR TITLE
fix(store): use lib0 sha256 when api not available

### PR DESCRIPTION
**Pull request by EYHN**
fix https://github.com/toeverything/AFFiNE/issues/6049

### CODE REVIEW

**Comment by darkskygit** [comment]
i don't think it's a good idea to maintain a hash implementation ourself
i think this library is more suitable: https://github.com/Daninet/hash-wasm , what do you think?

**Comment by fourdim** [comment]
What about lib0? We have already introduced it as a dependency. 
https://github.com/dmonad/lib0/blob/main/hash/sha256.js

**Review by doodlewind — COMMENTED** [review]
I'd say the idea using lib0 looks pretty nice!

**Review by Saul-Mirone — APPROVED** [review]

**Comment by Saul-Mirone** [comment]
The changes look good to me but I prefer the idea using lib0.

**Review by Brooooooklyn — CHANGES_REQUESTED** [review]
Let's use the impl in `lib0`

**Review by darkskygit — APPROVED** [review]

**Review by doodlewind — APPROVED** [review]

**Pull request merged**
