### PR TITLE
feat: edgeless text change color

### PR DESCRIPTION
**Pull request by lzlme**
Part of #4538

### CODE REVIEW

**Comment by hwangdev97** [comment]
If the content is placed, there should be no scrolling
shot-2023-09-14-22 05 05@2x
the design file:
shot-2023-09-14-22 06 16@2x

**Comment by donteatfriedrice** [comment]
Should we record the text color last selected like other tools, such as brush, shape. So that we can keep adding text with same color?


https://github.com/toeverything/blocksuite/assets/99816898/cf305fb8-c650-4611-a3f8-21c50c0e516e

**Comment by hwangdev97** [comment]
> Should we record the text color last selected like other tools, such as brush, shape, So that we can keep adding text with same color?
> 
>  Screen.Recording.2023-09-15.at.09.55.10.mov

yes cc @lzlme

**Comment by lzlme** [comment]
`color menu no scroll` and `color save` were done. @hwangdev97 @donteatfriedrice

**Review by hwangdev97 — APPROVED** [review]

**Review by donteatfriedrice — APPROVED** [review]

**Pull request merged**
