### PR TITLE
fix: point offset in edgeless default selection

### PR DESCRIPTION
**Pull request by himself65**

### CODE REVIEW

**Review by doodlewind — APPROVED** [review]
LGTM

**Comment by himself65** [comment]
Now selection on the default page also has the same issue. I will fix it in the next PR

**Comment by himself65** [comment]
I remove the padding on the body because It would cause test case to fail

**Comment by himself65** [comment]
> I remove the padding on the body because It would cause test case to fail

Also, I think we should detect the range//xywh by the relative position, not the absolute position on the screen

**Comment by doodlewind** [comment]
> > I remove the padding on the body because It would cause test case to fail
> 
> Also, I think we should detect the range//xywh by the relative position, not the absolute position on the screen

But `getBoundingClientRect` returns absolute position, and actually, we need to keep 2 coords systems in mind, one for model coords and one for final DOM absolute positions. Relative positions could be somewhat intermediate and interoperable with absolute ones.

**Pull request merged**
