### PR TITLE
drag resize handler in edgeless

### PR DESCRIPTION
**Pull request by SaikaSakura**

### CODE REVIEW

**Comment by doodlewind** [comment]
@SaikaSakura there are some discussion to be addressed, could you keep this PR open till our next peer interview? Thanks!

**Comment by doodlewind** [comment]
Whiteboard features are expected to be re-planned and this may require some refactoring, sorry that this PR may have to be blocked for a white.

**Comment by himself65** [comment]
Reassigned the PR to me today

**Comment by doodlewind** [comment]
This PR could be closed in favor of succeeding #247. Thanks for the original effort!

**Pull request closed without merging**
