### PR TITLE
feat: embed-linked-page card views and toolbar

### LINKED ISSUE #5713: Bookmark-linked page
[Design upgraded](https://www.figma.com/file/ry2HHWu5XafpuXBD2XOvKd/%F0%9F%9B%96-2023.S4?type=design&node-id=6755-23691&mode=design&t=zImYTax8CbHGkxX3-4)

Image

### PR DESCRIPTION
**Pull request by AyushAgrawal-A2**
closes #5713 

[Linked Page Playground Demo](https://blocksuite-git-fork-ayushagrawal-a2-ayush-5713-toeverything.vercel.app/starter/?init=linked)

Changes:
- Implemented Embed-Linked-Page (doc & editor)
- Implemented toolbar for inline page-ref
- Updated toolbar for card view (doc & edgeless)

### CODE REVIEW

**Review by Svaney-ssman — COMMENTED** [review]
Can you deal with the shadows that have been cropped on two sides
image

**Comment by Svaney-ssman** [comment]
This is a bug when I drag a deleted page from the note then turn into a large vertical view
image

**Comment by Svaney-ssman** [comment]
The placeholder images are not correct when I convert from horizontal view to vertical view, but correct after duplicate
image

**Review by houjoe0829 — APPROVED** [review]
Functionally, it meets expectations, and there are some UI details worth optimizing.

**Review by Flrande — APPROVED** [review]

**Review by doodlewind — COMMENTED** [review]
I think we need to rename the all `embed-linked-page` block type to `embed-linked-doc` due to product naming change from @houjoe0829

**Review by doodlewind — APPROVED** [review]
🎉

**Pull request merged**
