### PR TITLE
refactor(database): side detail title

### PR DESCRIPTION
**Pull request by golok727**
image
image

### CODE REVIEW

**Comment by golok727** [comment]
@zzj3720 PTAL👀

**Comment by zzj3720** [comment]
> @zzj3720 PTAL 👀. I opted not to use `renderUniLit` since it includes that icon, and I also wanted to incorporate a placeholder.

You should change the content of detailSlots.header, and renderUniLit simply renders detailSlots.header.

**Comment by zzj3720** [comment]
I noticed that you're not rendering the entire block here. Our design goal is to have the entire block styled in this area. For example, a todo list should have checkbox inside it, and currently, the icon also needs to be retained (as designed). Therefore, I don't think the placeholder issue should be fixed this way. We need a solution that preserves the complete block style.

**Comment by zzj3720** [comment]
Should I close this pull request for now and reopen a new one when we have a better solution? 
What do you think? @golok727

**Comment by golok727** [comment]
> Should I close this pull request for now and reopen a new one when we have a better solution? What do you think? @golok727

I opened this for the editing issue. I fixed the range issue I am opening a new PR. Closing!

**Comment by golok727** [comment]
> > Should I close this pull request for now and reopen a new one when we have a better solution? What do you think? @golok727
> 
> Actually I opened this for the editing issue. I fixed the range issue I am opening a new PR. Closing!

**Pull request closed without merging**
