### PR TITLE
feat(edgeless): support frame sidebar

### PR DESCRIPTION
**Pull request by donteatfriedrice**
Frames sidebar design: https://www.figma.com/file/ry2HHWu5XafpuXBD2XOvKd/%F0%9F%9B%96-2023.S4?node-id=2677%3A19552&mode=dev

Sidebar Header:
1. Support all frames setting. 
3. Enter presentation mode.

Sidebar Body:
1. Display all frame with real-time preview.
2. Support clicking to select frame.
4. Support shift-click to multi-select.
5. Support clicking blank area to de-select.
6. Support double click to fit the frame to screen.
7. Support dragging single frame or multiple frames to reorder.
8. Support Editing frame title.

### CODE REVIEW

**Review by doodlewind — APPROVED** [review]
In this iteration cycle, we should land this and finish the AFFiNE integration process, UI reviews feedback could be fixed in PRs afterwards.

**Comment by zanwei** [comment]
Had a discussion with @donteatfriedrice, there're some feedback needs to be update

1. Frame Sidebar still functions independently after switching back to Editor.
2. The style of the sidebar thumbnail Fill needs to be changed, please just refer to the design.
3. When Fill is turned on, the playback should fill the full screen. This is enough for now.

and also there're some UI feedback needs to be update

1. Please Update the `font-size` of title and serial number, also adjust the padding to 18px
image

2. Please make sure the title section is aligned with the content
image

**Comment by donteatfriedrice** [comment]
2. Support clicking to select frame.
3. Support shift-click to multi-select.
4. Support clicking blank area to de-select.
5. Support double click to fit the frame to screen.

https://github.com/toeverything/blocksuite/assets/99816898/c71e8764-a9dc-4a9e-83df-b3e1a3d503c0

**Comment by donteatfriedrice** [comment]
Feature:

6. Support enter presentation mode.

https://github.com/toeverything/blocksuite/assets/99816898/120da4f6-ec6b-45b3-9465-09fad579c44c

**Comment by donteatfriedrice** [comment]
Feature:
7. Support DnD to reorder frames.

https://github.com/toeverything/blocksuite/assets/99816898/13838346-8496-49e1-8dea-00d2d8c4f894

**Comment by donteatfriedrice** [comment]
Feature:

8. Support double click to switch to edgeless mode and navigate to the frame.

https://github.com/toeverything/blocksuite/assets/99816898/b693b080-ec4c-4e46-9786-16b00b74c1ab

**Comment by donteatfriedrice** [comment]
Feature:
9. Support editing frame title.

https://github.com/toeverything/blocksuite/assets/99816898/5ab88c49-f4c0-4b2a-a1f0-e081c1a1eafc

**Pull request merged**
