### PR TITLE
chore(blocks): refine surface ref toolbar

### PR DESCRIPTION
**Pull request by fundon**
Closes: [BS-870](https://linear.app/affine-design/issue/BS-870/surface-ref-toolbar)

### Before

Screenshot 2024-07-17 at 01 56 07

### After

Screenshot 2024-07-17 at 01 54 55
Screenshot 2024-07-17 at 01 54 51

### CODE REVIEW

**Comment by fundon** [comment]
* **#7595** <a href="https://app.graphite.dev/github/pr/toeverything/blocksuite/7595?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @fundon and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Saul-Mirone — APPROVED** [review]

**Comment by Svaney-ssman** [comment]
please change the interact state of toolbar
CleanShot 2024-07-18 at 11 10 33@2x

**Comment by fundon** [comment]
> please change the interact state of toolbar

I think that this should be a another issue. It can be fixed in a new PR, and the attachment toolbar is also a uniform problem.

**Comment by Saul-Mirone** [comment]
You can add the `merge` label if you want to merge the pr and get all the approves you need

**Pull request merged**
