### PR TITLE
fix(blocks): edit text on shape when it is transprent

### PR DESCRIPTION
**Pull request by fundon**
Closes [BS-784](https://linear.app/affine-design/issue/BS-784/无背景的shape，无法编辑文本内容)

https://github.com/user-attachments/assets/3bf3779b-a12b-4fcf-a972-b06b9cb6c4e3

### CODE REVIEW

**Comment by fundon** [comment]
* **#7838** <a href="https://app.graphite.dev/github/pr/toeverything/blocksuite/7838?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @fundon and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Saul-Mirone — COMMENTED** [review]
@doouding PTAL

**Comment by doouding** [comment]
Is this issue related to `filled` property?

**Comment by fundon** [comment]
> Is this issue related to `filled` property?

Before `color picker`, there is a logic about `filled` here:

https://github.com/toeverything/blocksuite/blob/4fa9f002a33082dcfb6f67c5f0466eae9f5344ef/packages/blocks/src/root-block/widgets/element-toolbar/change-shape-button.ts#L203-L209

**Review by doouding — APPROVED** [review]

**Pull request merged**
