### PR TITLE
feat: support embed-figma block type

### PR DESCRIPTION
**Pull request by AyushAgrawal-A2**
[Figma](https://www.figma.com/file/ry2HHWu5XafpuXBD2XOvKd/%F0%9F%9B%96-2023.S4?type=design&node-id=8603%3A36399&mode=dev)

Changes:
- Implemented Embed-Figma (doc & edgeless)
- Added to slash-menu & edgeless-toolbar
- Reload button on toolbar (doc & edgeless)

### CODE REVIEW

**Comment by Svaney-ssman** [comment]
Sorry for updating design late. We need to adjust dimensions of figma's embed view to match those of YouTube. The later embeds' size will be the same.

**Review by Svaney-ssman — COMMENTED** [review]
Sorry for updating design late. We need to adjust the dimensions of Figma's embed match to those of Youtube

**Review by Svaney-ssman — COMMENTED** [review]
1. remove this tooltip
image

2. caption button is missing in edgeless mode

**Review by doodlewind — COMMENTED** [review]
Seems that the button spacing may need to be fine-tuned.

image

**Comment by AyushAgrawal-A2** [comment]
> Seems that the button spacing may need to be fine-tuned.
> 
> image

@doodlewind done

image

**Review by doodlewind — APPROVED** [review]
Great progress! The timing is great, since we are launching next AFFiNE beta and this is a good point to be included.

**Pull request merged**
