### PR TITLE
feat: support multiple editor instance on the same page

### PR DESCRIPTION
**Pull request by zzj3720**
related #2396 
- Added an active state to the editor instance, only active editor can receive hotkey events.
- Only the virgo editor in the active editor can be focused
- Refactor tests to support automatically use in multiple editor instance scenarios after test cases been written.

### CODE REVIEW

**Comment by zzj3720** [comment]
@doodlewind Should I put other changes in a separate PR? I feel like this PR already contains too many code changes, which may make it difficult to review.

**Comment by doodlewind** [comment]
> @doodlewind Should I put other changes in a separate PR? I feel like this PR already contains too many code changes, which may make it difficult to review.

Would be great to split more PRs, thanks!

**Comment by zzj3720** [comment]
Currently, only basic.spec.ts has been passed.
I will complete the remaining parts in other PRs.

**Comment by zzj3720** [comment]
> > @doodlewind Should I put other changes in a separate PR? I feel like this PR already contains too many code changes, which may make it difficult to review.
> 
> Would be great to split more PRs, thanks!

@doodlewind Does this PR need to be split into smaller ones?

**Comment by Flrande** [comment]
> @doodlewind Does this PR need to be split into smaller ones?

I am reviewing this PR. :)

**Review by Flrande — APPROVED** [review]

**Comment by himself65** [comment]
I found a regression on AFFiNE that would cause page is missing

**Pull request merged**
