### PR TITLE
ci: add `codeql-analysis.yml`

### PR DESCRIPTION
**Pull request by himself65**

### CODE REVIEW

**Comment by doodlewind** [comment]
@lawvs found a REGEX blocker here. It would be great if you could take a look. Thanks!

**Comment by lawvs** [comment]
OK, I bypassed the scan by splitting the regex :)

**Comment by himself65** [comment]
lgtm

**Comment by doodlewind** [comment]
It costs 4min to complete CodeQL check, this slows us down. Can we make it run daily? For future multi-browser E2E testing, this kind of setup should be also useful.

**Comment by himself65** [comment]
> It costs 4min to complete CodeQL check, this slows us down. Can we make it run daily? For future multi-browser E2E testing, this kind of setup should be also useful.

I think there should have some cache on the following incremental commit?

**Comment by doodlewind** [comment]
> > It costs 4min to complete CodeQL check, this slows us down. Can we make it run daily? For future multi-browser E2E testing, this kind of setup should be also useful.
> 
> I think there should have some cache on the following incremental commit?

Well, let's just try committing some trivial refactoring here and see again 👀

**Comment by doodlewind** [comment]
I'd say the incremental run speed is still not very satisfying, especially for a check whose report is not our concern in maybe 99% of the time :(

I really want to make the CI process *faster* and *easier*, lots of effort has been done for reaching the current state. Daily running the CodeQL check seems to be more acceptable, though.

**Comment by himself65** [comment]
updated

**Comment by doodlewind** [comment]
Great improvement for our CI, thanks!

**Pull request merged**
