### PR TITLE
feat(playground): basic local-first collab playground support

### LINKED ISSUE #3588: Basic local-first playground collaboration functionality support

### PR DESCRIPTION
**Pull request by doouding**
close #3588 

## Significant change
- add runtime provider register api `registerProvider` on `workspace` and `store`
- original playground can be accessed through `http://localhost:5173/starter/`
- new playground files located on `playground/apps/default/`
- original playground files has been move to `playground/apps/starter/`

### CODE REVIEW

**Review by doodlewind — COMMENTED** [review]
Having `playground/src` and `playground/start/src` looks a bit duplicated and confusing. How about this structure that removes `/src` here:

```
examples (simple example for packages or prototyping)
  basic
  canvas
  virgo
  ...
apps (get `src` renamed)
  starter (legacy entry modules)
  default (new entry modules)

starter/index.html (allows quick access at `localhost:5173/starter/`, notice the final `/` is required)
index.html - (new entry HTML)
```

**Review by doodlewind — COMMENTED** [review]
`tsconfig.json` also requires update since some module resolving are not working in `start` (or `apps`).

**Comment by doouding** [comment]
I have modified the file directory structure and PR comment to reflect new changes.

**Review by doodlewind — APPROVED** [review]
Should get this landed, thanks!

**Pull request merged**
