### PR TITLE
feat: hide resize handles when dragging or resizing selected elements

### PR DESCRIPTION
**Pull request by pzppzz**
for a better experience?
hide all handles when dragging and hide all handles but the currently in use when resizing.

### CODE REVIEW

**Comment by L-Sun** [comment]
Cloud you provide a demo video showing the difference before and after the change?

**Comment by pzppzz** [comment]
> Cloud you provide a demo video showing the difference before and after the change?

The effect is same as Canva.

before:

https://github.com/toeverything/blocksuite/assets/89590352/0c1b1c0b-f2c6-4fed-a68b-4c0cd4644c79

after:

https://github.com/toeverything/blocksuite/assets/89590352/d94a6d01-970e-4c1e-82f4-5c5961963dbb

**Comment by L-Sun** [comment]
@hwangdev97 what do you think? 🤔

**Comment by golok727** [comment]
While moving elements works well, resizing should maintain the visibility and functionality of the handles, similar to Figma.

https://github.com/toeverything/blocksuite/assets/123532141/d45d4a49-cffc-4633-9359-b7a324824196

**Pull request closed without merging**
