### PR TITLE
feat: update code block style

### PR DESCRIPTION
**Pull request by zqran**
close: #1393

### CODE REVIEW

**Review by doodlewind — APPROVED** [review]
LGTM, thanks!

**Comment by LeuisKen** [comment]
I experience this problem too, and the `width: 89%` seems not the best fit for this issue.
This problem is caused by the `left: 40px` style of `.affine-code-block-container .ql-container` at [here](https://github.com/toeverything/blocksuite/blob/7449ab5aa58185852e63e296b7aafee20cd2964d/packages/blocks/src/code-block/code-block.ts#L155).
Due to this, maybe `width: calc(100% - 40px)` would be a better solution, and I think we need a comment to reference the relationship between these two things.
@doodlewind @zqran

**Comment by zqran** [comment]
@LeuisKen Thanks for your feedback. To be precise, we should determine the widths of 1 and 2 based on the UI design. This requires confirmation from @doodlewind .

image

**Comment by doodlewind** [comment]
> I experience this problem too, and the `width: 89%` seems not the best fit for this issue.
> 
> This problem is caused by the `left: 40px` style of `.affine-code-block-container .ql-container` at [here](https://github.com/toeverything/blocksuite/blob/7449ab5aa58185852e63e296b7aafee20cd2964d/packages/blocks/src/code-block/code-block.ts#L155).
> 
> Due to this, maybe `width: calc(100% - 40px)` would be a better solution, and I think we need a comment to reference the relationship between these two things.

Sounds great! I'm open to PR for tweaking here 😀

**Pull request merged**
