### PR TITLE
feat(page): support dropping blocks to the children of list item

### PR DESCRIPTION
**Pull request by wfnuser**
Since git settings not allow to reopen closed pull request #4961, I open a new pull request #3488 after solve the conflicts.
And I met some problems after I started to look at the test failures.

To close issue #3448 

>  I think there are some of the failures caused by the new drop in feature. If you do dragHandleFromBlockToBlockBottomById now, it will drop in the blocks not append it after the target block.
> How should I deal with it, change the dragHandleFromBlockToBlockBottomById implementation to make it behave like append not drop in? I'm not sure about it. Maybe I need some help. If someone can pair code with me will definitely help a lot. After the drop in feature been supported, many behavior might change I guess?

### CODE REVIEW

**Comment by donteatfriedrice** [comment]
> Since git settings not allow to reopen closed pull request #4961, I open a new pull request #3488 after solve the conflicts. And I met some problems after I started to look at the test failures.
> 
> > I think there are some of the failures caused by the new drop in feature. If you do dragHandleFromBlockToBlockBottomById now, it will drop in the blocks not append it after the target block.
> > How should I deal with it, change the dragHandleFromBlockToBlockBottomById implementation to make it behave like append not drop in? I'm not sure about it. Maybe I need some help. If someone can pair code with me will definitely help a lot. After the drop in feature been supported, many behavior might change I guess?

Thanks for your work! Because calcDropTarget is used in some other places and the drag handle functionality actually only needs a part of this function, I have extracted this part and written it as a separate utility function, which has been moved into the utils of the drag handle widget. As for testing dragHandleFromBlockToBlockBottomById, I have made some modifications to make it meet the previous requirements. Now I need some help from you to add a drop-into-related test, wondering if you have time? When implementing this test, you can pass the appropriate offset when calling the dragHandleFromBlockToBlockBottomById function to achieve the drop-into functionality. Thanks again for your hard work.

**Comment by wfnuser** [comment]
> Thanks for your work! Because calcDropTarget is used in some other places and the drag handle functionality actually only needs a part of this function, I have extracted this part and written it as a separate utility function, which has been moved into the utils of the drag handle widget. As for testing function dragHandleFromBlockToBlockBottomById, I have made some modifications to make it meet the previous requirements. Now I need some help from you to add a drop-into-related test, wondering if you have time? When implementing this test, you can pass the appropriate offset when calling the dragHandleFromBlockToBlockBottomById function to achieve the drop-into functionality. Thanks again for your hard work.
 
I'm glad to help and explore more about this project. Let me check your changes first. So I can just append a new commit for tests in this branch?
 BTW, good job.

**Comment by donteatfriedrice** [comment]
> > Thanks for your work! Because calcDropTarget is used in some other places and the drag handle functionality actually only needs a part of this function, I have extracted this part and written it as a separate utility function, which has been moved into the utils of the drag handle widget. As for testing function dragHandleFromBlockToBlockBottomById, I have made some modifications to make it meet the previous requirements. Now I need some help from you to add a drop-into-related test, wondering if you have time? When implementing this test, you can pass the appropriate offset when calling the dragHandleFromBlockToBlockBottomById function to achieve the drop-into functionality. Thanks again for your hard work.
> 
> I'm glad to help and explore more about this project. Let me check your changes first. So I can just append a new commit for tests in this branch? BTW, good job.

Yeah, you can continue to push commit to this pr. Please be sure pull the update to your codebase firstly. Thanks!

**Comment by wfnuser** [comment]
@donteatfriedrice Sorry for the late update. I just supplemented one test for drop in block. Please check it out.

**Review by doodlewind — APPROVED** [review]
LGTM, having the dropped position from sibling to children helps making the dropped content becoming collapsible. Thank for the feat!

**Pull request merged**
