### PR TITLE
feat(edgeless): paste SVG in text/plain mime

### PR DESCRIPTION
**Pull request by golok727**
# Changes
- This PR allows to paste SVG in text format from the clipboard

# Usage
- Copy as SVG from tools like Figma and directly paste it into edgeless

### CODE REVIEW

**Comment by golok727** [comment]
@doodlewind  do we need sanitization? as scripts in SVG usually do not get executed.

**Review by Saul-Mirone — DISMISSED** [review]
Please add integration test for this case.

**Comment by fourdim** [comment]
> @doodlewind do we need sanitization? as scripts in SVG usually do not get executed. Also we are loading it as image src

Yeah, we do need to sanitize it.

**Comment by golok727** [comment]
> > @doodlewind do we need sanitization? as scripts in SVG usually do not get executed. Also we are loading it as image src
> 
> Yeah, we do need to sanitize it

Is a simple sanitization like below enough or does blocksuite uses any specific tool? haven't found anything yet.

```ts
const attributes = Array.from(svgEl.attributes).map(({ name }) => name)
 const hasScriptAttr = !!attributes.find((attr) => attr.startsWith('on'))
 const disallowedSvgElements = svgEl.querySelectorAll(svgDisallowed.join(','))
  return disallowedSvgElements.length === 0 && !hasScriptAttr ? svg : null
```

**Comment by fourdim** [comment]
> > > @doodlewind do we need sanitization? as scripts in SVG usually do not get executed. Also we are loading it as image src
> > 
> > 
> > Yeah, we do need to sanitize it
> 
> Is a simple sanitization like below enough or does blocksuite uses any specific tool? haven't found anything yet.
> 
> ```ts
> const attributes = Array.from(svgEl.attributes).map(({ name }) => name)
>  const hasScriptAttr = !!attributes.find((attr) => attr.startsWith('on'))
>  const disallowedSvgElements = svgEl.querySelectorAll(svgDisallowed.join(','))
>   return disallowedSvgElements.length === 0 && !hasScriptAttr ? svg : null
> ```

You can use https://www.npmjs.com/package/dompurify.

**Comment by golok727** [comment]
@fourdim PTAL

**Review by fourdim — APPROVED** [review]

**Pull request merged**
