### PR TITLE
refactor: use typescript@5 const type param for `matchFlavours`

### PR DESCRIPTION
**Pull request by Saul-Mirone**

### CODE REVIEW

**Comment by doodlewind** [comment]
Wait for upstream TS 5.0 support from playwright

**Comment by Saul-Mirone** [comment]
Seems playwright has upgraded the typescript version. We need to wait for them to release the changes.

https://github.com/microsoft/playwright/issues/21900

**Review by himself65 — APPROVED** [review]

**Comment by himself65** [comment]
`Test / Playground E2E test (3) (pull_request)` crashed, any idea?

**Comment by Saul-Mirone** [comment]
> `Test / Playground E2E test (3) (pull_request)` crashed, any idea?

I tried a lot of ways but still can not reproduce in my environment. I think it might be a playwright bug in nightly version.

**Comment by Saul-Mirone** [comment]
Update: still waiting for @playwright/test@1.33.0.

**Comment by himself65** [comment]
https://github.com/microsoft/playwright/releases/tag/v1.33.0

**Pull request merged**
