### PR TITLE
fix(edgeless): align shape component toolbar with UI design

### LINKED ISSUE #4113: Shape component toolbar should align with UI design
Design:

Screenshot 2023-08-16 at 09 52 29

### PR DESCRIPTION
**Pull request by donteatfriedrice**
To close #4113

### CODE REVIEW

**Review by xell — CHANGES_REQUESTED** [review]
Thanks. The icon size(s) and the interval spacing still need to refine.

**Comment by donteatfriedrice** [comment]
Screenshot 2023-08-16 at 21 39 45

Screenshot 2023-08-16 at 21 41 50

Screenshot 2023-08-16 at 21 45 49

Screenshot 2023-08-16 at 21 47 14

Screenshot 2023-08-16 at 21 48 51

Screenshot 2023-08-16 at 22 31 44

**Review by xell — APPROVED** [review]
The new revision is great and sets a good example for others by the side-by-side comparisons of the design and pixel-wise implementations.

**Review by doodlewind — APPROVED** [review]
Let's land this, cheers!

**Pull request merged**
