### PR TITLE
perf: faster tick for snapshot

### PR DESCRIPTION
**Pull request by doodlewind**
This tries to optimize #8380

### CODE REVIEW

**Comment by fourdim** [comment]
I do think it's much better to add a parameter in this function.
RequestIdleCallback will schedule the task to a not near future compared to promise.resolve, if I remember correctly.

**Comment by doodlewind** [comment]
@fourdim `queueMicroTask` could be much faster (but jams the UI). I'm just not sure why we make async loading by default.

```js
function testNextTick(useRequestIdleCallback, iterations = 1000) {
  const nextTick = useRequestIdleCallback
    ? (callback) => requestIdleCallback(() => callback())
    : (callback) => queueMicrotask(() => callback());

  return new Promise((resolve) => {
    const startTime = performance.now();
    let count = 0;

    function runIteration() {
      if (count < iterations) {
        nextTick(() => {
          count++;
          runIteration();
        });
      } else {
        const endTime = performance.now();
        resolve(endTime - startTime);
      }
    }

    runIteration();
  });
}

async function runTest() {
  console.log('Starting performance test...');

  const rICTime = await testNextTick(true);
  console.log(`requestIdleCallback: ${rICTime.toFixed(2)}ms`);

  const qMTTime = await testNextTick(false);
  console.log(`queueMicrotask: ${qMTTime.toFixed(2)}ms`);

  const difference = Math.abs(rICTime - qMTTime);
  const fasterMethod = rICTime < qMTTime ? 'requestIdleCallback' : 'queueMicrotask';

  console.log(`\nDifference: ${difference.toFixed(2)}ms`);
  console.log(`${fasterMethod} is faster in this test.`);
}

runTest();
```

```
requestIdleCallback: 63213.20ms
queueMicrotask: 4.10ms
```

**Comment by fourdim** [comment]
We won't jam the UI becuase we have batch import function which reserves the time for UI to response.

**Comment by doodlewind** [comment]
> We won't jam the UI becuase we have batch import function which reserves the time for UI to response.

Here is also the code path when pasting very long content, see #7796

**Pull request closed without merging**
