### PR TITLE
feat(virgo): ctrl delete to delete one word forward

### LINKED ISSUE #3566: Support CTRL + Del to delete one word forward
### Description

Delete one word to the right like in any other program.

### Use case

I rely on this keybind a lot.

### Anything else?

https://defkey.com/what-means/ctrl-del
### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by lzlme**
resolve #3566

### CODE REVIEW

**Review by Flrande — CHANGES_REQUESTED** [review]
We should handle native [inputType](https://www.w3.org/TR/input-events-2/#interface-InputEvent-Attributes) in [transform-input](https://github.com/toeverything/blocksuite/blob/75669fcb78d7f8f11132d9245b5030504d006cba/packages/virgo/src/utils/transform-input.ts#L154).

**Comment by lzlme** [comment]
> We should handle native [inputType](https://www.w3.org/TR/input-events-2/#interface-InputEvent-Attributes) in [transform-input](https://github.com/toeverything/blocksuite/blob/75669fcb78d7f8f11132d9245b5030504d006cba/packages/virgo/src/utils/transform-input.ts#L154).

Well, what is a good way to let `transformInput` know that `ctrl-delete` is pressed? Should `_ctrlDelete` be passed as a parameter to `transformInput`? And then handle it like this ?
```javascript
case 'deleteContentBackward':
case 'deleteByCut': {
  if (ctrlDelete) {
    handleWordDelete(editor, vRange);
    return
  }
  handleDelete(vRange, editor);
  return;
}
```

**Comment by Flrande** [comment]
> Well, what is a good way to let transformInput know that ctrl-delete is pressed? Should _ctrlDelete be passed as a parameter to transformInput? And then handle it like this ?

If it is a native behavior you don't need to know `ctrl-delete` and you can judge it using `deleteWordForward` (see it in [inputType](https://www.w3.org/TR/input-events-2/#interface-InputEvent-Attributes))

It it is not a native behavior you should not implement it in virgo and you should implement it in [defineKeyMap](https://github.com/toeverything/blocksuite/blob/75669fcb78d7f8f11132d9245b5030504d006cba/packages/blocks/src/__internal__/service/index.ts#L157).

**Review by lawvs — COMMENTED** [review]
Could you add some tests for it?

**Comment by lzlme** [comment]
> Could you add some tests for it?

Sure

**Review by Flrande — APPROVED** [review]

**Pull request merged**
