### PR TITLE
fix(blocks): url parse and paste

### PR DESCRIPTION
**Pull request by fundon**
Closes [BS-1356](https://linear.app/affine-design/issue/BS-1356/识别以-结尾的链接时，-末尾-会被忽略)

### CODE REVIEW

**Comment by fundon** [comment]
* **#8233** <a href="https://app.graphite.dev/github/pr/toeverything/blocksuite/8233?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @fundon and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Saul-Mirone — APPROVED** [review]

**Comment by fourdim** [comment]
Memo: replace this fix with upstream updates.
https://github.com/micromark/micromark-extension-gfm-autolink-literal/issues/11

**Review by Magken91 — APPROVED** [review]

**Comment by fourdim** [comment]
https://github.com/github/markup/issues/980
Could you please reconsider this change?@fundon @Saul-Mirone

**Comment by fundon** [comment]
@fourdim 
Only ensures that the behavior of copy block to link is correct on AFFiNE's side.

I also recommend modifying the upstream. This logic can be deleted.

**Comment by fundon** [comment]
If a text fragment does not start with _ but starts with a link protocol, it should be recognized as a link first.

**Comment by fourdim** [comment]
> I also recommend modifying the upstream. This logic can be deleted.

They refused to do so to preserve the same behavior with GitHub markdown.

**Comment by fourdim** [comment]
Anyway, I will maintain status quo.

**Pull request merged**
