### PR TITLE
fix: `compareDocumentPosition` usage

### PR DESCRIPTION
**Pull request by zuozijian3720**
https://developer.mozilla.org/en-US/docs/Web/API/Node/compareDocumentPosition

image

image

The code

```ts
a.compareDocumentPosition(b) === Node.DOCUMENT_POSITION_CONTAINED_BY
```

means that `a` is an ancestor of `b`, so `a` inside `b` may need implemented by 

```ts
b.compareDocumentPosition(a) === Node. DOCUMENT_POSITION_CONTAINED_BY
```

---
btw:
The magic number 20 should be refactored to 

```ts
Node.DOCUMENT_POSITION_CONTAINED_BY | Node.DOCUMENT_POSITION_FOLLOWING
```

I'm not sure what this code does, it just improves readability

### CODE REVIEW

**Comment by zuozijian3720** [comment]
Let me check why the test failed

**Comment by zuozijian3720** [comment]
Seemingly, the test failure is expected.🤔

**Comment by Flrande** [comment]
> Seemingly, the test failure is expected.🤔

Why?

**Comment by zuozijian3720** [comment]
> > Seemingly, the test failure is expected.🤔
> 
> Why?

I just tested the blockuite and AFFiNE master branches and also could not select the previous line by `shift+up`.
Maybe I'm wrong. I will check again.

**Comment by Flrande** [comment]
Virgo test run in https://blocksuite-toeverything.vercel.app/examples/virgo/

**Comment by zuozijian3720** [comment]
> Virgo test run in https://blocksuite-toeverything.vercel.app/examples/virgo/

Thanks for the info, I have fixed this bug

**Review by Flrande — APPROVED** [review]

**Pull request merged**
