### PR TITLE
feat(edgeless): upgrade shape text tool bar

### PR DESCRIPTION
**Pull request by donteatfriedrice**
Related #3714 

https://github.com/toeverything/blocksuite/assets/99816898/c1556620-0f5f-4e09-aa17-e66f66bb19c5

### CODE REVIEW

**Review by Svaney-ssman — CHANGES_REQUESTED** [review]
1. align icons are wrongimage
check design: 
image


2. shape don't have auto layout by text size
image

**Comment by donteatfriedrice** [comment]
> 1. align icons are wrongimage
>    check design:
> 
> image
> 2. shape don't have auto layout by text size
> 
> image

https://github.com/toeverything/blocksuite/assets/99816898/ee782d36-5126-4097-849d-23605030a8c3

**Comment by Svaney-ssman** [comment]
A small change by design: change normal [shape text] color from [pure white] to [pure black]. The black background text color is fine now, no need to change it. 
check [design preview](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/%F0%9F%97%92%EF%B8%8F-AFFiNE-2023?type=design&node-id=12712-188780&mode=design&t=LSc7LVxoyeaEmagR-4) @donteatfriedrice

**Comment by donteatfriedrice** [comment]
> A small change by design: change normal [shape text] color from [pure white] to [pure black]. The black background text color is fine now, no need to change it. check [design preview](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/%F0%9F%97%92%EF%B8%8F-AFFiNE-2023?type=design&node-id=12712-188780&mode=design&t=LSc7LVxoyeaEmagR-4) @donteatfriedrice

Screenshot 2023-08-21 at 17 03 21

**Review by Svaney-ssman — APPROVED** [review]
LGTM

**Review by doodlewind — APPROVED** [review]
Let's land this, great collaboration you guys!

**Pull request merged**
