### PR TITLE
fix(blocks): photos field is optional in tweet media

### PR DESCRIPTION
**Pull request by fundon**
Closes [BS-1075](https://linear.app/affine-design/issue/BS-1075/抓取的-tweet-中-photos-可能是可选)
See https://github.com/FixTweet/FxTwitter/wiki/Status-Fetch-API#embeds

### CODE REVIEW

**Comment by fundon** [comment]
* **#7887** <a href="https://app.graphite.dev/github/pr/toeverything/blocksuite/7887?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @fundon and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Saul-Mirone — APPROVED** [review]
LGTM, do we also need to update code in `title` and `icon`?

**Comment by fundon** [comment]
Let me check it.

**Comment by fundon** [comment]
It should be safe. The `author` field is required.

**Pull request merged**
