### PR TITLE
fix: format bar action status

### LINKED ISSUE #1197: Format Bar Action status is not responsive
If I do `undo`, format bar status not updated.

https://user-images.githubusercontent.com/41265413/218983286-76d3567d-5ec8-49bb-8054-778acf9ddb82.mov

### PR DESCRIPTION
**Pull request by devlzl**
fix #1197

### CODE REVIEW

**Comment by lawvs** [comment]
Do you have time to add some tests?

**Review by lawvs — APPROVED** [review]

**Comment by himself65** [comment]
need to sign up CLA before merging

**Comment by lzlme** [comment]
> Do you have time to add some tests?

I have a problem.
I open playground and test it manually, no problem; but when I write the following test code, it always fails.
```js
test('should format quick bar action status updated while undo', async ({
  page,
}) => {
  await enterPlaygroundRoom(page);
  await initEmptyParagraphState(page);
  await focusRichText(page);
  await type(page, 'helloworld');
  await dragBetweenIndices(page, [0, 0], [0, 7]);

  const formatQuickBar = page.locator(`.format-quick-bar`);
  const boldBtn = formatQuickBar.locator(`[data-testid=bold]`);

  await expect(boldBtn).not.toHaveAttribute('active', '');
  await boldBtn.click();
  await expect(boldBtn).toHaveAttribute('active', '');
  await undoByKeyboard(page);
  await expect(boldBtn).not.toHaveAttribute('active', '');
});


// Error: expect(received).not.toHaveAttribute(expected)
// Expected string: not ""
// Received string: ""
```

**Comment by lzlme** [comment]
> need to sign up CLA before merging

I am happy to do that, but how exactly should I sign ?

**Comment by himself65** [comment]
> > need to sign up CLA before merging
> 
> I am happy to do that, but how exactly should I sign ?

at the bottom of this file 

https://github.com/toeverything/blocksuite/blob/master/.github/CLA.md

**Comment by himself65** [comment]
> > Do you have time to add some tests?
> 
> I have a problem. I open playground and test it manually, no problem; but when I write the following test code, it always fails.
> 
> ```js
> test('should format quick bar action status updated while undo', async ({
>   page,
> }) => {
>   await enterPlaygroundRoom(page);
>   await initEmptyParagraphState(page);
>   await focusRichText(page);
>   await type(page, 'helloworld');
>   await dragBetweenIndices(page, [0, 0], [0, 7]);
> 
>   const formatQuickBar = page.locator(`.format-quick-bar`);
>   const boldBtn = formatQuickBar.locator(`[data-testid=bold]`);
> 
>   await expect(boldBtn).not.toHaveAttribute('active', '');
>   await boldBtn.click();
>   await expect(boldBtn).toHaveAttribute('active', '');
>   await undoByKeyboard(page);
>   await expect(boldBtn).not.toHaveAttribute('active', '');
> });
> 
> 
> // Error: expect(received).not.toHaveAttribute(expected)
> // Expected string: not ""
> // Received string: ""
> ```

I tried, but the status still needs to be updated. I think it's indeed a error

**Comment by himself65** [comment]
codecov crashed. ignore it

**Comment by himself65** [comment]
> > > Do you have time to add some tests?
> > 
> > 
> > I have a problem. I open playground and test it manually, no problem; but when I write the following test code, it always fails.
> > ```js
> > test('should format quick bar action status updated while undo', async ({
> >   page,
> > }) => {
> >   await enterPlaygroundRoom(page);
> >   await initEmptyParagraphState(page);
> >   await focusRichText(page);
> >   await type(page, 'helloworld');
> >   await dragBetweenIndices(page, [0, 0], [0, 7]);
> > 
> >   const formatQuickBar = page.locator(`.format-quick-bar`);
> >   const boldBtn = formatQuickBar.locator(`[data-testid=bold]`);
> > 
> >   await expect(boldBtn).not.toHaveAttribute('active', '');
> >   await boldBtn.click();
> >   await expect(boldBtn).toHaveAttribute('active', '');
> >   await undoByKeyboard(page);
> >   await expect(boldBtn).not.toHaveAttribute('active', '');
> > });
> > 
> > 
> > // Error: expect(received).not.toHaveAttribute(expected)
> > // Expected string: not ""
> > // Received string: ""
> > ```
> 
> I tried, but the status still needs to be updated. I think it's indeed a error

Looks like the E2E test result is different from the real result. investigating this

**Comment by lawvs** [comment]
> Looks like the E2E test result is different from the real result. investigating this

This behavior is expected because updating the format status in the `render` is unreliable. It works locally since the redo triggers the `selectionchange` event, and re-render UI.

However, in the end-to-end environment, the `selectionchange` event is not emitted during redo, causing it to fail.

We should consider refactoring it once the redo/undo event is implemented.

See also

https://github.com/toeverything/blocksuite/blob/a5814e376158c723323683a3b338e9956f9578b1/packages/blocks/src/components/format-quick-bar/index.ts#L111-L127

**Pull request merged**
