### PR TITLE
feat: new edgeless toolbar icon

### PR DESCRIPTION
**Pull request by lzlme**
related to #4538 
new pen and eraser icon

### CODE REVIEW

**Review by donteatfriedrice — APPROVED** [review]
It looks cool.

**Comment by hwangdev97** [comment]
I think the icon style of shape can be updated now?

shot-2023-09-12-14 29 49@2x

**Comment by lzlme** [comment]
> I think the icon style of shape can be updated now?
> 
> shot-2023-09-12-14 29 49@2x

Because shape and related animations are relatively complex, I plan to open a new PR to deal with them specifically.

**Comment by hwangdev97** [comment]
shot-2023-09-12-15 20 35@2x

Ok, up arrow, you need to use this color

shot-2023-09-12-15 21 00@2x

**Review by hwangdev97 — APPROVED** [review]

**Pull request merged**
