### PR TITLE
chore(blocks): refine linked web toolbar

### PR DESCRIPTION
**Pull request by fundon**
Closes: [BS-583](https://linear.app/affine-design/issue/BS-583/linked-web-toolbar)

### CODE REVIEW

**Comment by fundon** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/toeverything/blocksuite/7479?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#7479** <a href="https://app.graphite.dev/github/pr/toeverything/blocksuite/7479?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#7475** <a href="https://app.graphite.dev/github/pr/toeverything/blocksuite/7475?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @fundon and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by Svaney-ssman** [comment]
UI Issues:

1. Need to display the url more concisely, please refer to the link display in card view: [check in figma](https://www.figma.com/design/UTTtfVCcStw1dKUg0gCSPo/%F0%9F%93%9A-Design-System?node-id=22606-49970&t=bN7iR4bqeja24YQG-4)
CleanShot 2024-07-04 at 17 22 29@2x

2. the default button of " inline/card/embed transition" has no background, this is a hover state
CleanShot 2024-07-04 at 17 24 36@2x

**Comment by fundon** [comment]
> 1. Need to display the url in toolbar more concisely, please refer to the link display in card view: [check in figma](https://www.figma.com/design/UTTtfVCcStw1dKUg0gCSPo/%F0%9F%93%9A-Design-System?node-id=22606-49970&t=bN7iR4bqeja24YQG-4)

So only domain names are displayed here?

**Comment by Svaney-ssman** [comment]
> Visit Preview

Yes! please align text to the left
CleanShot 2024-07-05 at 10 35 47@2x
CleanShot 2024-07-05 at 10 37 30@2x

**Comment by Svaney-ssman** [comment]
It seems the font weight and button default state have not changed yet
CleanShot 2024-07-05 at 10 42 38@2x

**Review by Saul-Mirone — APPROVED** [review]
LGTM

**Review by doodlewind — APPROVED** [review]

**Pull request merged**
