### PR TITLE
fix(page): added delete-item hover color 

### PR DESCRIPTION
**Pull request by RajeevDash007**
fixed: #4298 
Screenshot (101)

### CODE REVIEW

**Comment by fourdim** [comment]
https://github.com/toeverything/design/issues/55
Only red on hover

**Comment by hwangdev97** [comment]
I saw:
shot-2023-08-23-11 28 40@2x

but our design:

I think an icon needs to be added here

shot-2023-08-23-11 30 12@2x

cc @zanwei

**Comment by RajeevDash007** [comment]
> I saw: shot-2023-08-23-11 28 40@2x
> 
> but our design:
> 
> I think an icon needs to be added here
> 
> shot-2023-08-23-11 30 12@2x
> 
> cc @zanwei

I have added the delete icon

**Comment by Svaney-ssman** [comment]
> I have added the delete icon

The delete icon and the edit icon, check [detail here](https://www.figma.com/file/rfH3P9Wbz4IEp2Ai18O8dV/%E2%96%B6%EF%B8%8F-Affine.2023.Late?type=design&node-id=6513-76089&mode=design&t=70TublfX83PwtRQo-4)

**Comment by Svaney-ssman** [comment]
The delete icon, and the edit icon
default status, hover status are also missing, don't forget the blue shadow in the active status
check [design ](https://www.figma.com/file/rfH3P9Wbz4IEp2Ai18O8dV/%E2%96%B6%EF%B8%8F-Affine.2023.Late?type=design&node-id=6513-76089&mode=design&t=70TublfX83PwtRQo-4)

**Comment by zanwei** [comment]
default status, hover status are also missing, don't forget the blue shadow in the active status
check [design](https://www.figma.com/file/rfH3P9Wbz4IEp2Ai18O8dV/%E2%96%B6%EF%B8%8F-Affine.2023.Late?type=design&node-id=6513-76089&mode=design&t=Q9mXn7KuOI0N5A9k-4) 

image

**Comment by zzj3720** [comment]
> default status, hover status are also missing, don't forget the blue shadow in the active status check [design](https://www.figma.com/file/rfH3P9Wbz4IEp2Ai18O8dV/%E2%96%B6%EF%B8%8F-Affine.2023.Late?type=design&node-id=6513-76089&mode=design&t=Q9mXn7KuOI0N5A9k-4)↳
> 
> image

The menu UI refactoring is not yet complete, I think we just need to simply fix the UI of delete for now, and I'll finish the menu UI refactoring in the next iteration.

**Comment by doodlewind** [comment]
> The menu UI refactoring is not yet complete, I think we just need to simply fix the UI of delete for now, and I'll finish the menu UI refactoring in the next iteration.

Yes, @xell I think we need to distinguish the `type:feat` and `type:bug` for UI issues. Having the standalone fixes landed atomically should match our policy.

**Comment by RajeevDash007** [comment]
> > default status, hover status are also missing, don't forget the blue shadow in the active status check [design](https://www.figma.com/file/rfH3P9Wbz4IEp2Ai18O8dV/%E2%96%B6%EF%B8%8F-Affine.2023.Late?type=design&node-id=6513-76089&mode=design&t=Q9mXn7KuOI0N5A9k-4)↳
> > 
> > image
> 
> The menu UI refactoring is not yet complete, I think we just need to simply fix the UI of delete for now, and I'll finish the menu UI refactoring in the next iteration.

I guess, I have done that, Kindly check it and if you need any  changes then let me know

**Review by Svaney-ssman — APPROVED** [review]
As @zzj3720  said approve this issue firstly

**Review by zanwei — APPROVED** [review]

**Pull request merged**
