### PR TITLE
chore(blocks): adjust connector shapes order

### PR DESCRIPTION
**Pull request by fundon**
Closes [BS-521](https://linear.app/affine-design/issue/BS-521/调整-connector-toolbar-上-shapes-顺序)

### CODE REVIEW

**Comment by fundon** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/toeverything/blocksuite/7300?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#7301** <a href="https://app.graphite.dev/github/pr/toeverything/blocksuite/7301?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#7300** <a href="https://app.graphite.dev/github/pr/toeverything/blocksuite/7300?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#7299** <a href="https://app.graphite.dev/github/pr/toeverything/blocksuite/7299?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @fundon and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Svaney-ssman — COMMENTED** [review]
Please also update the icons of connector shape, [check the design](https://www.figma.com/design/UTTtfVCcStw1dKUg0gCSPo/%F0%9F%93%9A-Design-System?node-id=22050-56267&t=rNA9P5VV1AQT2GmW-4)
CleanShot 2024-06-13 at 10 06 38@2x

**Comment by fundon** [comment]
> Please also update the icons of connector shape

Updated. Please check it again.

**Review by Saul-Mirone — APPROVED** [review]

**Review by Svaney-ssman — APPROVED** [review]
Thank you❤️

**Pull request merged**
