### PR TITLE
fix: arrow buttons are disabled when kanban exists in page

### PR DESCRIPTION
**Pull request by ununian**
iShot_2024-02-20_16 56 02

### CODE REVIEW

**Comment by ununian** [comment]
@doodlewind please cc

**Review by doodlewind — APPROVED** [review]
LGTM

**Review by doodlewind — COMMENTED** [review]
Could you update the CLA.md? Thanks!

**Review by doodlewind — APPROVED** [review]
Welcome and thanks again for the fix!

**Pull request merged**
