### PR TITLE
refactor: rename page to doc

### LINKED ISSUE #6214: Renaming `page` to `doc`
We should rename the `Page` class to `Doc`, so the `page.addBlock` would be `doc.addBlock`, which would reflect the doc-based (or file-based) organization of workspace better. This also aligns the planned product feature exposing more doc types. 

Note that the scope of this PR should be limited to API surface. The `affine:page` block type in data would be kept for compatibility.

### PR DESCRIPTION
**Pull request by AyushAgrawal-A2**
[TOV-561](https://linear.app/affine-design/issue/TOV-561/renaming-page-to-doc)
closes #6214 

Before this pr, we have 
- `Page` (store), 
- `PageBlock` (having `page` and `edgeless` views)  
- `pageMode` (have `page` and `edgeless` mode)

To avoid any confusion due to name overlap, I have renamed:
 - `Page` (store) to `Doc`
 - `PageBlock` to `RootBlock`, (this is in line with syntax `doc.root` & `doc.slots.rootAddedOn`. flavour is still "affine:page")
 - `pageMode` to `editorMode`, having 2 modes - `page`, `edgeless`

So now - 
 - "page" word is now used only when related to `page` editorMode.
 - "edgeless" word is now used only when related to `edgeless` editorMode.
 - doc refers to store object only.
 - root refers to root block only.

Exception -
 - `pageId` is renamed to `docId`, (everywhere, except in block props & snapshot payload)
 - `pageVersion` & `pages` properties in `WorkspaceMetaState`
 - `page` property in `BlockModel` (this is marked as deprecated and expected usage is via `doc` getter and setter)

Change log - https://app.affine.pro/share/63a1780d-ee20-4b7f-ac70-f254e4154120/rduRN-2fxFklR-nLSZVYe

### CODE REVIEW

**Review by doodlewind — COMMENTED** [review]
Thanks for the great work!

I think we should not do the `PageBlock` -> `RootBlock` rename, using current naming should align better the product design in AFFiNE.

Current build errors are related to doc link, running `pnpm build` in the docs package should be adequate.

**Comment by AyushAgrawal-A2** [comment]
> Current build errors are related to doc link, running `pnpm build` in the docs package should be adequate.

@doodlewind 
I am yet to make changes in docs package, links are broken and text has to be updated.... currently reviewing my changes again...
will fix it

**Comment by Flrande** [comment]
> Page (store) to Doc
> PageBlock to RootBlock, (this is in line with syntax doc.root & doc.slots.rootAddedOn. flavour is still "affine:page")
> pageMode to editorMode, having 2 modes - page, edgeless

How about this?

`PageBlock ` -> `DocBlock`
`DocPageBlockComponent` -> `PageDocBlockComponent`
`EdgelessPageBlockComponent` -> `EdgelessDocBlockComponent`

**Comment by doodlewind** [comment]
@Flrande after discussion, I think the `RootBlock` one with `affine:page` flavour makes sense since it avoids most naming inconsistencies in cases. So it's LGTM to proceed with current renaming plan 🫡

**Comment by AyushAgrawal-A2** [comment]
> > Page (store) to Doc
> > PageBlock to RootBlock, (this is in line with syntax doc.root & doc.slots.rootAddedOn. flavour is still "affine:page")
> > pageMode to editorMode, having 2 modes - page, edgeless
> 
> How about this?
> 
> `PageBlock` -> `DocBlock` `DocPageBlockComponent` -> `PageDocBlockComponent` `EdgelessPageBlockComponent` -> `EdgelessDocBlockComponent`

@Flrande 
It will create a overlap of `doc` keyword, Doc(store) object and DocBlock
Open to suggestion for any other name for PageBlock, excluding already used keywords

**Review by doodlewind — APPROVED** [review]

**Review by doodlewind — COMMENTED** [review]
Have double checked that this doesn't break data, we'll hand over and focus on the next step bumping AFFiNE.

**Pull request merged**
