### PR TITLE
fix: align arrow icon in page info

### PR DESCRIPTION
**Pull request by RajeevDash007**
fixed: #3883 
BlockSuite-Playground

If you need any changes then let me know.
Thank you so much for your assistance.

### CODE REVIEW

**Comment by RajeevDash007** [comment]
@JimmFly just check this PR once

**Comment by JimmFly** [comment]
Splendid, @xell , is this precisely what you desire?

**Comment by RajeevDash007** [comment]
@xell will that be okay?
Screenshot (7)

**Review by xell — COMMENTED** [review]
The alignment is better now. But the class name would be better to use `link-icon` or something like that to reflect the fact that it is associated with an icon named `DualLinkIcon`, by which it's beneficial for the future code explanation, searching and debug, among others.

**Comment by doodlewind** [comment]
@xell for naming related reviews, it's recommended to directly push to the PR branch, this could make the review process more efficient.

**Review by xell — APPROVED** [review]

**Comment by doodlewind** [comment]
Should land this for further testing in AFFiNE, thanks @RajeevDash007 for the collaboration!

**Pull request merged**
