### PR TITLE
fix: image selection offset

### LINKED ISSUE #1192: Image selection offset
Image

### PR DESCRIPTION
**Pull request by fundon**
Fixes: #1192

### CODE REVIEW

**Comment by fundon** [comment]
Is this the right behavior?
Screenshot 2023-02-16 at 1 56 22 PM

**Comment by himself65** [comment]
> Is this the right behavior?
> 
> Screenshot 2023-02-16 at 1 56 22 PM
> 
> 

I don't think so

**Comment by fundon** [comment]
1. Set `type` to `embed` when clicking on the image.
2. Set `type` to `block` when selecting blocks.

**Comment by doodlewind** [comment]
Testing CI setup here, please ignore the closing and re-open operation.

**Review by doodlewind — APPROVED** [review]
LGTM, thanks for the timely fix!

**Pull request merged**
