### PR TITLE
fix(edgeless): incorrect cursor style of selected rect

### PR DESCRIPTION
**Pull request by L-Sun**
Fix incorrect cursor style of the selected rectangle due to mismatched coordinates.

### CODE REVIEW

**Comment by L-Sun** [comment]
* **#6983** <a href="https://app.graphite.dev/github/pr/toeverything/blocksuite/6983?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @L-Sun and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by fundon** [comment]
When resizing, we can also consider updating cursor style.


https://github.com/toeverything/blocksuite/assets/27926/95554a64-ae03-4360-8565-2b94b566ddc2

**Review by doodlewind — APPROVED** [review]
LGTM, great enhancement on the test case!

**Comment by doodlewind** [comment]
@L-Sun you don't have to mark labels for PRs, they are used for classifying issues.

**Pull request merged**
