### PR TITLE
fix: start backspace after list

### LINKED ISSUE #382: Some types of blocks cannot be entered at the beginning of the next line through Backspace
Cannot enter the Bulleted List, Numbered List, and To-do List at the beginning of the next line through Backspace

20221220153935_rec_

### PR DESCRIPTION
**Pull request by Flrande**
fix #382 

20221220174259_rec_

### CODE REVIEW

**Comment by doodlewind** [comment]
Good catch! Although it may seem excessive, could you add a test case about this corner case? I think our test suite has covered all the utils that could help you write the operation sequence semantically. Thanks!

**Comment by Flrande** [comment]
done

**Review by doodlewind — APPROVED** [review]
To speed up test case execution, merging these three cases into one case will be better (we can use `undo` to recover previous state), since the constant cost of opening a browser window is much more than doing common rich text editing operations. But that could be the content of another PR about optimization. let's land this one for now, thanks!

**Comment by Flrande** [comment]
Do I need to create a pr for this optimization? I can do this work later.

**Comment by doodlewind** [comment]
> Do I need to create a pr for this optimization? I can do this work later.

Just a suggestion, feel free to arrange it at your wish :)

**Comment by Flrande** [comment]
All right.😇

**Pull request merged**
