### PR TITLE
feat(edgeless): connector supports text label

### PR DESCRIPTION
**Pull request by fundon**
The connector supports text label.
There are three modes in connector: `Straight` `Orthogonal` `Curve`, need to be handled separately.

### Connector Label

* Add
    - [x] By button, default position is at the center of the path
    - [x] By double-clicked position, along the path
* Edit
    * [x] By button
    * [x] By double-clicking `connector`
    * [x] By double-clicking `label`
* Select
    * [x] Show component toolbar
    * [x] Adjust styles: `font`, `color`
    * [x] Adjust index: `front` `back`
    * [x] Support for moving along the path
    * [x] Auto adjust position when adjusting connector's source or target
* Remove
    * [x] Select `Label`, and press `Delete`
    * [x] Select `Connector` and `Label`, and press `Delete` or `CMD+A` + `Delete`
    * [x] Select `Connector`, and press `Delete`, `Label` will also be deleted
* Selection
   *  [x] Select both connector and label `should only show the connector's toolbar`

- [ ] fix selection(`shift+` click) 
- [ ] fix snap
- [ ] fix tests
- [ ] add tests

### Updates

This will be split into smaller PRs.

* Feat: add connector label [#7106](https://github.com/toeverything/blocksuite/pull/7106)

### CODE REVIEW

**Comment by fundon** [comment]
* **#6665** <a href="https://app.graphite.dev/github/pr/toeverything/blocksuite/6665?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @fundon and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by doodlewind — COMMENTED** [review]
The data structure updates should be listed in PR description.

**Comment by fundon** [comment]
I think Connector Label should be a standalone element to support selection, adjusting styles, dragging and dropping to move the position, adjusting the index.

**Comment by doouding** [comment]
Is there any special with connector text comparing to shape text?

**Comment by fundon** [comment]
> Is there any special with connector text comparing to shape text?

1. text can be selected
2. supported by 1, move on the path(curve)
3. supported by 1, adjust style and index

**Comment by golok727** [comment]
https://github.com/toeverything/blocksuite/issues/6583

**Pull request closed without merging**
