### PR TITLE
feat: update edgeless color palette

### PR DESCRIPTION
**Pull request by fundon**
Closes: [BS-1804](https://linear.app/affine-design/issue/BS-1804/border-color色板影响的yuan素), [BS-1803](https://linear.app/affine-design/issue/BS-1803/fill-color色板影响的yuan素)

### What's Changed

* refactor `EdgelessLineWidthPanel` component, the previous width is fixed and cannot be used in the new design
* refactor `EdgelessColorPanel` and `EdgelessColorButton` components, make them simple and reusable
* delete redundant `EdgelessOneRowColorPanel` component
* unity and update color palette, if the previously set color is not in the latest color palette, the custom color button will be selected

### CODE REVIEW

**Comment by fundon** [comment]
* **#8762** <a href="https://app.graphite.dev/github/pr/toeverything/blocksuite/8762?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/toeverything/blocksuite/8762?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `master`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by doodlewind — APPROVED** [review]

**Comment by Saul-Mirone** [comment]
Please move the pr to affine

**Comment by fundon** [comment]
> Please move the pr to affine

moving

**Comment by fundon** [comment]
https://github.com/toeverything/AFFiNE/pull/9243

**Pull request closed without merging**
