### PR TITLE
 fix: enter shortcut on focusing embed block or its caption

### PR DESCRIPTION
**Pull request by DiamondThree**

### CODE REVIEW

**Comment by himself65** [comment]
add a test case?

**Comment by doodlewind** [comment]
Yes, and the case name could just be `enter shortcut on focusing embed block and its caption` 👀

**Comment by DiamondThree** [comment]
> enter shortcut on focusing embed block and its caption
 thanks , that's a good idea,I will fix

**Comment by doodlewind** [comment]
For quick iteration, we are going to merge this with the `housekeeping needed` label added. We'll plan a stage for cleaning up tech debts afterward.

**Pull request merged**
