### PR TITLE
fix: size report workflow

### LINKED ISSUE #5408: The size report CI action failed
See the recent output result here:

https://github.com/toeverything/blocksuite/actions/workflows/size-report.yml

### PR DESCRIPTION
**Pull request by Rachit1313**
**Description:**

This pull request addresses a TypeScript type error in the `vite.config.size.ts` file. The issue was related to the type inference of the `base` configuration. TypeScript was expecting a function call, but `base` was a function itself.

To resolve this, I explicitly annotated the type of the `base` configuration in `vite.config.size.ts` file. Additionally, I ensured that the `base` function is called with the required parameter `{ mode: process.env.NODE_ENV }` in the `vite.config.size.ts` file.

These changes fix the TypeScript type errors and allow for a smooth build process.

**Changes Made:**
- Modified `vite.config.size.ts` to call the `base` function with the necessary parameter.

**Testing:**
- Tested the changes locally to ensure there are no TypeScript type errors.
- Verified that the build process completes successfully after the modifications.

This resolves issue #5408 
close #5408

### CODE REVIEW

**Comment by Rachit1313** [comment]
image
This commit passed all the tests on the forked repo.

**Comment by Rachit1313** [comment]
@doouding / @doodlewind , Could you please guide with the PR title lint and regarding the test. It passed in my forked repo, Is that possible for you to re run the failed jobs?

**Comment by Rachit1313** [comment]
@doodlewind , The PR title lint still failed

**Comment by Rachit1313** [comment]
> @doodlewind , The PR title lint still failed

Except the PR title lint, everything passed

**Comment by Rachit1313** [comment]
@doodlewind , Can you link issue #5408

**Comment by doodlewind** [comment]
@Rachit1313 I think you can simply add "close #xxx" in your PR description.

**Comment by Rachit1313** [comment]
> @Rachit1313 I think you can simply add "close #xxx" in your PR description.

Done, Thanks. Every check is passing except PR title lint, not sure why?

**Comment by Rachit1313** [comment]
failed with ✖ scope must be one of [page, edgeless, database, virgo, store, std, playground]

**Comment by Rachit1313** [comment]
> failed with ✖ scope must be one of [page, edgeless, database, virgo, store, std, playground]

@doodlewind Based on your lint file, ["page", "edgeless", "database", "virgo", "store", "std", "playground"] These are the only scopes supported and I don't see ci or cu here.

**Comment by Rachit1313** [comment]
@doodlewind , good to go. Let me know if any changes are required before merging?

**Review by doodlewind — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
