### PR TITLE
chore(blocks): update note default settings

### PR DESCRIPTION
**Pull request by fundon**
Closes: [BS-334](https://linear.app/affine-design/issue/BS-334/note-default-state-reset)

Update note default settings:

* set background to `--affine-note-background-blue`
* set border style to `none`
* set border radius to `0`
* set shadow to `sticker`

**Does it require data migration?**

Hopefully someone will remove the xml from the test, it's too expensive to maintain.

### CODE REVIEW

**Comment by fundon** [comment]
* **#7303** <a href="https://app.graphite.dev/github/pr/toeverything/blocksuite/7303?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @fundon and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by doouding — APPROVED** [review]

**Review by Saul-Mirone — APPROVED** [review]

**Comment by Svaney-ssman** [comment]
The border style solid icon is incorrect
CleanShot 2024-06-14 at 13 39 14@2x
[ Go to design👉](https://www.figma.com/design/UTTtfVCcStw1dKUg0gCSPo/%F0%9F%93%9A-Design-System?node-id=17998-47819&t=jF7H5oHoV5gBxhWy-4)
image

**Comment by Svaney-ssman** [comment]
In the color picker, a 0.5px border for white and black is suggested to recognize
CleanShot 2024-06-14 at 13 42 30@2x
[check design👉](https://www.figma.com/design/UTTtfVCcStw1dKUg0gCSPo/%F0%9F%93%9A-Design-System?node-id=17998-45336&t=jF7H5oHoV5gBxhWy-4)
CleanShot 2024-06-14 at 13 44 32@2x

**Comment by fundon** [comment]
@Svaney-ssman Fixed, please check it again.

**Comment by Svaney-ssman** [comment]
> @Svaney-ssman Fixed, please check it again.

All fixed, but the quick connecter icons looked smaller than others?
CleanShot 2024-06-14 at 15 20 26@2x
CleanShot 2024-06-14 at 15 20 17@2x
CleanShot 2024-06-14 at 15 20 06@2x

**Comment by fundon** [comment]
> All fixed, but the quick connecter icons looked smaller than others?

Good catch!

**Comment by fundon** [comment]
> All fixed, but the quick connecter icons looked smaller than others?

Please check it again.

**Review by Svaney-ssman — APPROVED** [review]
GooGood👍

**Pull request merged**
