### PR TITLE
fix(database): sum shows too many digits after decimal point

### LINKED ISSUE #8815: ​Sum function prints too many digits after decimal point
### What happened?

Too many digits after decimal point. The sum should be 165.45.
It seems to happens due to float point calculation.

It happens only on some combinations of sums.

image

### Distribution version

Web (affine.fail)

### What browsers are you seeing the problem on if you're using web version?

Chrome, Other

### Are you self-hosting?

- [ ] Yes

### Relevant log output

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by OlegDev1**
Fixes #8815 
Fixes **floating-point precision error**, when calculating the sum of the column

I can write some unit tests, but unfortunately there are no unit tests in `data-view` folder. Any guidance will be highly appreciated

**Before the fix**:
Screenshot 2024-11-30 at 13 44 42

**After the fix**:
Screenshot 2024-11-30 at 13 44 53

### CODE REVIEW

**Review by zzj3720 — APPROVED** [review]

**Comment by Flrande** [comment]
### Merge activity

* **Dec 2, 3:36 AM EST**: The merge label 'merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=toeverything&repo=blocksuite) once it meets the requirements.

**Comment by OlegDev1** [comment]
Thank you for starting the merging process of my PR! I have updated my branch to the latest changes

If any changes / additions are required - please let me know, I am happy to help!

**Review by doodlewind — APPROVED** [review]

**Review by doodlewind — COMMENTED** [review]
Could you sign the CLA for helping us land this PR? Thanks!

**Comment by OlegDev1** [comment]
@doodlewind I have signed the CLI, thank you very much! 

Could you please provide some good first issues?
I really love the flexibility and speed of Affine and want to help with development process. The fact that separate component library was developed specifically to meet Affine's needs is very impressive. I can write tests, fix bugs, or anything. Thanks!

**Review by doodlewind — COMMENTED** [review]
Landed the patch, thanks for your contribution!

**Pull request merged**
