### PR TITLE
fix(database): can't edit database side layout title

### PR DESCRIPTION
**Pull request by golok727**
Related to https://github.com/toeverything/blocksuite/pull/6858
Closes https://github.com/toeverything/blocksuite/issues/6832 (1)

### CODE REVIEW

**Comment by golok727** [comment]
@zzj3720 if this is done then we can easily add the placeholder

```ts
 //TODO(@Flrande) wrap placeholder in `rich-text` or inline-editor to make it more developer-friendly
  private _updatePlaceholder = () => {
    if (
      !this._placeholderContainer ||
      !this._richTextElement ||
      !this.inlineEditor
    )
      return;

    if (
      this.doc.readonly ||
      this.inlineEditor.yTextLength > 0 ||
      this.inlineEditor.isComposing ||
      !this.selected ||
      this._isInDatabase()
    ) {
      this._placeholderContainer.classList.remove('visible');
    } else {
      this._placeholderContainer.classList.add('visible');
    }
  };

```

**Comment by golok727** [comment]
This has bugs in edgeless. As it is attached to the root element it scrolls with the viewport in edgeless.

**Comment by zzj3720** [comment]
The root cause of this bug is using `renderModel` to render single block. According to the current technical plan, it should be replaced with `renderSpecPortal`. However, I'm not sure how to use `renderSpecPortal` to only render a block that nested inside a database block. I need to discuss this with @Saul-Mirone.

**Comment by golok727** [comment]
@zzj3720 should I close this for now ?

**Pull request closed without merging**
