### PR TITLE
feat(edgeless): add frame toolbar

### LINKED ISSUE #4089: Support creating frame by keyboard shortcut
Create Frame: F

- When a component is selected, pressing F can quickly create a frame.
- When no component is selected, pressing F activates the "create frame" function in the creation toolbar. Related with https://github.com/toeverything/blocksuite/issues/4088

### LINKED ISSUE #4185: Add Frame button for edgeless toolbar
shot-2023-08-17-16 36 49@2x

add frame button and sub menu for edgeless toolbar

[the figma file link](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/%F0%9F%97%92%EF%B8%8F-AFFiNE-2023?type=design&node-id=12149%3A34024&mode=design&t=hiEgCXDAlGXmACSP-1)

shot-2023-08-17-16 59 52@2x

There are two sets of behaviors to handle here: 

1. By default, clicking the button activates the custom state. And user can define the area and create a frame.  And the Cursors needs change to:

shot-2023-08-17-17 03 11@2x

3. When user click 1:1 or 16:9 button, edgeless will auto add new frame in the canvas.

### PR DESCRIPTION
**Pull request by regischen**
close #4185 
close #4089

### CODE REVIEW

**Review by doodlewind — COMMENTED** [review]
Damn, this is FAST!

**Review by xell — APPROVED** [review]
Well done. Generally LGTM.

**Comment by hwangdev97** [comment]
Would anyone modify the margins of these icons? 😢

image

**Comment by hwangdev97** [comment]
I think, frame need a tooltip, like 'Frame' and add shortcut `f` @houjoe0829

**Comment by houjoe0829** [comment]
> I think, frame need a tooltip, like 'Frame' and add shortcut `f` @houjoe0829

Tracking here https://github.com/toeverything/blocksuite/issues/4089

**Pull request merged**
