### PR TITLE
revert: feat(sync): add blob engine (#6937)

### PR DESCRIPTION
**Pull request by fourdim**
This reverts 5a6af5ebdc7a7f8b71e7cffdd3d7d89c36d6dc6b.

DOMException: Failed to execute 'put' on 'IDBObjectStore': #<Promise> could not be cloned.
    at http://localhost:5173/node_modules/.vite/deps/idb-keyval.js?v=23ee0c59:28:11
    at http://localhost:5173/node_modules/.vite/deps/idb-keyval.js?v=23ee0c59:14:49
    at async IndexedDBBlobSource.set (http://localhost:5173/@fs/home/username/te/blocksuite/packages/framework/sync/src/blob/impl/indexeddb.ts:19:5)
    at async BlobEngine.set (http://localhost:5173/@fs/home/username/te/blocksuite/packages/framework/sync/src/blob/engine.ts:110:5)
    at async http://localhost:5173/@fs/home/username/te/blocksuite/packages/blocks/src/root-block/edgeless/edgeless-root-block.ts:337:24
    at async Promise.all (index 0)
    at async EdgelessRootBlockComponent.addImages (http://localhost:5173/@fs/home/username/te/blocksuite/packages/blocks/src/root-block/edgeless/edgeless-root-block.ts:354:5)
    at async onDrop (http://localhost:5173/@fs/home/username/te/blocksuite/packages/blocks/src/image-block/image-service.ts:46:11)

### CODE REVIEW

**Comment by fourdim** [comment]
* **#7140** <a href="https://app.graphite.dev/github/pr/toeverything/blocksuite/7140?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @fourdim and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by Flrande** [comment]
Need more details

**Comment by fourdim** [comment]
Just drop an image in edgeless mode.

**Comment by Flrande** [comment]
fixed in #7137

**Pull request closed without merging**
