### PR TITLE
Initial Dockerfile and docker-compose.yml for Docker support

### PR DESCRIPTION
**Pull request by as-shura**
Is it possible to review this in a way that we can continue using this inside of Docker?

### CODE REVIEW

**Review by himself65 — COMMENTED** [review]
/cc @darkskygit

**Comment by doodlewind** [comment]
I don't think the BlockSuite framework and the playground is an app to be reused via Docker. We will keep using the native tool chain for building and testing it. But we have planned docker support for http://affine.pro and this will be landed very soon tho.

**Comment by doodlewind** [comment]
Or else, could you elaborate your use case?

**Comment by doodlewind** [comment]
It's recommended to use [StackBlitz](https://stackblitz.com/github/toeverything/blocksuite) and [CodeSandbox](https://codesandbox.io/p/github/toeverything/blocksuite/master) for hosting cross-platform debugging environment (and we are open to PR that reflects this in our BUILDING.md docs), and this one should be closed since for BlockSuite, we don't have further plan (including docs and regression maintenance) on docker support.

**Pull request closed without merging**
