### PR TITLE
feat(database): select supports single selection and multiple selection modes

### PR DESCRIPTION
**Pull request by zqran**

### CODE REVIEW

**Review by Himself65 — DISMISSED** [review]
image


click `Create xxx` not working

**Comment by zqran** [comment]
> image
> 
> click `Create xxx` not working

done

**Comment by zqran** [comment]
In order to reuse the Select component to support both single and multiple selections, I made the following modifications to the type:

```diff
- class SelectCell extends DatabaseCellLitElement<string>
+ class SelectCell extends DatabaseCellLitElement<string[]>
```

In single mode, the value is: `[value]`.
In multi mode, the value is: `[...selectedValue, value]`.

e.g.

```ts
// judge single or multi modes: 
const newValue = this.isSingleMode ? [value] : [...selectedValue, value];
this.rowHost.setValue(newValue);
```

**Review by doodlewind — APPROVED** [review]
Thanks for adding new column type!

**Pull request merged**
