### PR TITLE
feat(edgeless): new note slicer

### PR DESCRIPTION
**Pull request by donteatfriedrice**
[TOV-191](https://linear.app/affine-design/issue/TOV-191/剪刀逻辑的优化)

New note slicer:
- [x] Add a cutting mode button on note toolbar to be used to toggle note slicer setting and store it in session storage.

Screenshot 2024-01-19 at 02 48 47

- [x] Update slicer button ui style and position.
- [x] Change slice indicator to block dividing lines. And active line will be shown with animation.

Screenshot 2024-01-19 at 15 00 39

- [x] The note cut will inherit the properties of last note.

https://github.com/toeverything/blocksuite/assets/99816898/2730cf34-e8aa-4046-a381-ce975338d481

- [x] Add shortcut '-' for cutting mode. When select one note, press '-' can toggle cutting mode

### CODE REVIEW

**Comment by hwangdev97** [comment]
maybe the button should be align with the dosh line ? cc @zanwei 

shot-2024-01-19-14 35 06@2x

**Comment by Svaney-ssman** [comment]
Should the note exit cutting mode after the user click outside the note or do other operations? @hwangdev97 @zanwei

**Comment by zanwei** [comment]
Had a discussion internally, there're few changes need to be modified.

1. After the user cuts the note, the cut mode will not be saved.
2. We gonna add a shortcut to active the cut mode easily.
3. Drag handle should be disabled when cut mode is activated.

cc @donteatfriedrice

**Review by doodlewind — APPROVED** [review]
LGTM, thanks for the feat!

**Review by zanwei — APPROVED** [review]

**Pull request merged**
