### PR TITLE
fix(edgeless): selection when all elements are connectors

### PR DESCRIPTION
**Pull request by fundon**
Closes: BS-94

### CODE REVIEW

**Comment by fundon** [comment]
* **#6652** <a href="https://app.graphite.dev/github/pr/toeverything/blocksuite/6652?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @fundon and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by fundon** [comment]
The next PR will fix the resize connectors.

**Review by Saul-Mirone — APPROVED** [review]

**Comment by Saul-Mirone** [comment]
@fundon seem there're some conflicts.

**Comment by fundon** [comment]
> seem there're some conflicts.

any screenshots or videos?

**Pull request merged**
