### PR TITLE
perf: disable hmr plugin by default

### PR DESCRIPTION
**Pull request by pengx17**
It seems the HMR plugin will cause serious performance issues in development mode, especially for the heavy example.
Need to disable it before upstream is fixed.

In the performance profiling report, there are many tiny tasks within `__web-dev-server__/wc-hmr/runtime.js`, which is in the hmrPlugin:
image

cc @fi3ework

### CODE REVIEW

**Review by doodlewind — COMMENTED** [review]
Perhaps we can make non-hmr mode (instead of `dev:hmr`) by default?

**Comment by pengx17** [comment]
@fi3ework for the time being using HMR mode, I've noticed that sometimes the plugin doesn't re-register event handlers after an update. As a result, I frequently have to perform a full page reload manually. While I believe that HMR has the potential to greatly enhance the developer experience (DX), I think that the current version of the wc-hmr plugin falls short in comparison to similar plugins available for React and Vue.

**Comment by lawvs** [comment]
Also related to https://github.com/toeverything/blocksuite/issues/1244

**Comment by pengx17** [comment]
@lawvs Thanks for the additional insights on this issue!
I would assume it may take quite some effort to fix this issue upstream. I think we can vote on whether or not to enable HMR by default?

**Review by doodlewind — APPROVED** [review]

**Comment by doodlewind** [comment]
Let's just land the fallback and I've added #1244 into out roadmap for metrics.

**Pull request merged**
