### PR TITLE
feat(page): support universal list toggle

### PR DESCRIPTION
**Pull request by lawvs**
Fix https://github.com/toeverything/blocksuite/issues/2945

- [x] Add toggle for list
- [x] Update editor layout
- [x] Update drag handle
- [x] Fix tests
- [x] Add new tests for toggle list
- [x] Update the `theme` package
  - See https://github.com/toeverything/design/pull/90
- [x] Update mobile padding
  - `@media screen and (max-width: 640px)`

Credits to https://github.com/toeverything/blocksuite/pull/1139

## Side effects

- Now a new class `with-drag-handle` will be added to block elements when the drag handle hovering
- Update `--affine-editor-width` from 800px to 944px
- Update `affine-doc-page-block-container` padding from 24px to 96px
- Update playwright viewport from 900px to 960px

---

https://github.com/toeverything/blocksuite/assets/18554747/868a95d6-5102-41ed-8618-bc8e2c5785fa

### CODE REVIEW

**Comment by hwangdev97** [comment]
I think when we active drag handle, the toggle icon should display. 

shot-2023-09-13-19 55 17@2x

**Review by hwangdev97 — APPROVED** [review]

**Comment by hwangdev97** [comment]
For UI/UX, it’s ok 👍👍👍👍

**Comment by donteatfriedrice** [comment]
In edgeless mode, drag handle looks like being out of note when there is a toggle list, maybe need to optimize the offset left in edgeless mode.

https://github.com/toeverything/blocksuite/assets/99816898/0bb18a99-a5ba-4e69-a96c-cf8b9674a8c4

**Comment by hwangdev97** [comment]
> In edgeless mode, drag handle looks like being out of note when there is a toggle list, maybe need to optimize the offset left in edgeless mode or expand the note padding?
> 
>  Screen.Recording.2023-09-15.at.11.08.01.mov

We will modify the note editing state of edgeless so that it can be better compatible with related content, so there is no need to process it in this PR.

**Review by doodlewind — APPROVED** [review]
This has been a long journey and we should land this, thanks for the effort!

**Pull request merged**
