### PR TITLE
refactor: `affine:group` -> `affine:frame`

### PR DESCRIPTION
**Pull request by doodlewind**
* [x] cleanup `group` concept
* [x] data compatibility & migration
* [x] unit test

### CODE REVIEW

**Review by himself65 — CHANGES_REQUESTED** [review]
this is a breaking change. could you please try to make forward compatibility

**Comment by lawvs** [comment]
I plan to implement an `assertDocMatchJSX` similar to `assertStoreMatchJSX` function but ignores all elements of edgeless( frame and shape), what do you think?

**Comment by doodlewind** [comment]
> this is a breaking change. could you please try to make forward compatibility

Certainly, we need to do the `group` -> `frame` conversion in `syncFromExistingDoc`, and I'll use the binary in #510 for local testing.

**Comment by doodlewind** [comment]
> I plan to implement an `assertDocMatchJSX` similar to `assertStoreMatchJSX` function but ignores all elements of edgeless( frame and shape), what do you think?

Will this feature require having YDoc binary as expected state? Since the binary is not readable, I'm not sure if committing YDoc binaries into our repo is an good idea.

**Comment by himself65** [comment]
> > this is a breaking change. could you please try to make forward compatibility
> 
> Sure, we need to do the `group` -> `frame` conversion in `syncFromExistingDoc`, and I'll use the binary in #510 for local testing.

we could put a basic old version binary into test fixtures, and do a unit test into store

**Comment by doodlewind** [comment]
@thorseraq is this test case flaky? https://github.com/toeverything/blocksuite/actions/runs/3835526880/jobs/6528878731

**Comment by thorseraq** [comment]
> @thorseraq is this test case flaky? https://github.com/toeverything/blocksuite/actions/runs/3835526880/jobs/6528878731

end position of mouse drag seems exceeding text area in CI environment

**Review by himself65 — APPROVED** [review]

**Pull request merged**
