### PR TITLE
fix: cut for multi-block selection

### PR DESCRIPTION
**Pull request by lzlme**
fix: #1385 

I fixed this bug, but there is a small problem: when I write a test, why do I have to call selectAllByKeyboard twice to select all blocks, if I call it only once, only the current block is selected.

### CODE REVIEW

**Comment by hcmind** [comment]
@doodlewind Hi, I'm having some testing problems.
When I submitted the PR I found that it did not pass the E2E test,
So I undid all the changes locally and ran the `pnpm test`, but still 4 of the tests failed. Shouldn't all tests pass for unchanged code ?

**Comment by lzlme** [comment]
@doodlewind 
Hi, I'm having some testing problems.
When I submitted the PR I found that it did not pass the E2E test,
So I undid all the changes locally and ran the pnpm test, but still 4 of the tests failed. Shouldn't all tests pass for unchanged code ?

**Comment by doodlewind** [comment]
> fix: #1385 
> 
> 
> 
> I fixed this bug, but there is a small problem: when I write a test, why do I have to call selectAllByKeyboard twice to select all blocks, if I call it only once, only the current block is selected.

The twice-selected behavior is by design and is also what some popular block editors implements (e.g, lark).

**Comment by doodlewind** [comment]
> @doodlewind 
> 
> Hi, I'm having some testing problems.
> 
> When I submitted the PR I found that it did not pass the E2E test,
> 
> So I undid all the changes locally and ran the pnpm test, but still 4 of the tests failed. Shouldn't all tests pass for unchanged code ?

Not sure if it's reproducible. Maybe running them standalone (with `test.only` or VSCode plugin) can help?

**Comment by lzlme** [comment]
@doodlewind I passed the playwright test, but there is an error when `uploading to https://codecov.io`. What should I do ?

**Review by lawvs — APPROVED** [review]

**Review by doodlewind — APPROVED** [review]

**Pull request merged**
