### PR TITLE
fix: clear selection when press esc keydown

### LINKED ISSUE #990: Pressing escape doesn't cancel current selection state
Reproduce:

1. Open playground
2. single click anywhere
3. notice that the selection is following you
4. try to press escape key
5. notice it doesn't work as expected (to stop the selection process)

also:
1. make a selection by dragging over text
2. try to press escape key
3. notice it doesn't work as expected (to remove the selection)

### PR DESCRIPTION
**Pull request by Innei**

### CODE REVIEW

**Comment by Innei** [comment]
Press ESC down.

https://user-images.githubusercontent.com/41265413/216769841-5e796dbd-b04c-4757-bc45-d20adf3fcd1b.mov

**Comment by himself65** [comment]
```
Error: Unexpected console message: TypeError: Cannot read properties of undefined (reading 'emit')
```

**Comment by lawvs** [comment]
After pressing ESC, pressing Backspace can still delete selected blocks, I think it's related to https://github.com/toeverything/blocksuite/issues/933

**Comment by Innei** [comment]
> After pressing ESC, pressing Backspace can still delete selected blocks, I think it's related to #933

Fixed.

**Review by lawvs — APPROVED** [review]

**Pull request merged**
