### PR TITLE
fix: revert .nvmrc

### PR DESCRIPTION
**Pull request by doodlewind**

### CODE REVIEW

**Review by himself65 — COMMENTED** [review]
Cloudflare even not support 18?

**Comment by doodlewind** [comment]
I think `revert` is also a valid commit type in https://github.com/conventional-changelog/commitlint, anyway both are fine

**Comment by darkskygit** [comment]
> > Cloudflare even not support 18?
> 
> Not sure, just trying. /cc @darkskygit
> 
> P.S. I think `revert` is also a valid commit type in https://github.com/conventional-changelog/commitlint, anyway both are fine

What's the problem? I didn't find the context.

**Comment by himself65** [comment]
> > > Cloudflare even not support 18?
> > 
> > 
> > Not sure, just trying. /cc @darkskygit
> > P.S. I think `revert` is also a valid commit type in https://github.com/conventional-changelog/commitlint, anyway both are fine
> 
> What's the problem? I didn't find the context.

Upgrade nvmrc to 18 cause it crashes

**Comment by darkskygit** [comment]
> > > > Cloudflare even not support 18?
> > > 
> > > 
> > > Not sure, just trying. /cc @darkskygit
> > > P.S. I think `revert` is also a valid commit type in https://github.com/conventional-changelog/commitlint, anyway both are fine
> > 
> > 
> > What's the problem? I didn't find the context.
> 
> Upgrade nvmrc to 18 cause it crashes

Which PR is it in? Let me take a look at the log.

**Comment by himself65** [comment]
> > > > > Cloudflare even not support 18?
> > > > 
> > > > 
> > > > Not sure, just trying. /cc @darkskygit
> > > > P.S. I think `revert` is also a valid commit type in https://github.com/conventional-changelog/commitlint, anyway both are fine
> > > 
> > > 
> > > What's the problem? I didn't find the context.
> > 
> > 
> > Upgrade nvmrc to 18 cause it crashes
> 
> Which PR is it in? Let me take a look at the log.

https://github.com/toeverything/blocksuite/commit/498454d8a24e8b660e6a06f6d66f2e019ff0b44a

**Comment by darkskygit** [comment]
> > > > > > Cloudflare even not support 18?
> > > > > 
> > > > > 
> > > > > Not sure, just trying. /cc @darkskygit
> > > > > P.S. I think `revert` is also a valid commit type in https://github.com/conventional-changelog/commitlint, anyway both are fine
> > > > 
> > > > 
> > > > What's the problem? I didn't find the context.
> > > 
> > > 
> > > Upgrade nvmrc to 18 cause it crashes
> > 
> > 
> > Which PR is it in? Let me take a look at the log.
> 
> [498454d](https://github.com/toeverything/blocksuite/commit/498454d8a24e8b660e6a06f6d66f2e019ff0b44a)

image

I confirmed that the current pages support up to 17, and it is expected that any version can be supported after the v2 version is launched:

https://github.com/cloudflare/pages-build-image/discussions/1

**Pull request merged**
