### PR TITLE
feat: support for indenting and unindenting multi-level blocks

### LINKED ISSUE #2862: Support using tab to indent multiple highlighted list lines with different indent levels
### What happened?

- I have multiple lines of text, 
- I click and drag to select those lines of text
- once selected/highlighted, I push the tab key.

Expected outcome after pushing tab:
- all lines of highlighted text should indent on the editor. Pushing shift tab should unindent all lines of highlighted text.

Current outcome:
- multiple lines of highlighted text don't indent when pushing tab key.

Using Linux app.

### Version

app.affine.pro

### What browsers are you seeing the problem on?

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by donteatfriedrice**
To close #2862 

1. [x] Current implementation of intenation.
indent-multi-level-blocks

- [x] Unindentation of multi-level blocks
- [x] Add E2E Test

### CODE REVIEW

**Comment by donteatfriedrice** [comment]
Current effects:

https://github.com/toeverything/blocksuite/assets/99816898/57f43e76-a43a-4cbf-9162-d141d879b6b9

**Comment by donteatfriedrice** [comment]
2. Current effects for unindentation:

https://github.com/toeverything/blocksuite/assets/99816898/9e7a672e-d640-42bc-84f2-fcf01e96e7b2

**Comment by donteatfriedrice** [comment]
@doodlewind In the CI process, it seems that the error below often occurs, is there any way to solve it?

Screenshot 2023-06-16 at 16 16 53

**Comment by doodlewind** [comment]
Retry! 😈

**Review by doodlewind — APPROVED** [review]
This looks pretty neat, thanks!

**Pull request merged**
