### PR TITLE
chore(blocks): refine link creation panel

### PR DESCRIPTION
**Pull request by fundon**
Closes: [BS-723](https://linear.app/affine-design/issue/BS-723/create-link)

Screenshot 2024-07-10 at 13 32 11

### CODE REVIEW

**Comment by fundon** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/toeverything/blocksuite/7490?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#7490** <a href="https://app.graphite.dev/github/pr/toeverything/blocksuite/7490?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#7483** <a href="https://app.graphite.dev/github/pr/toeverything/blocksuite/7483?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#7479** <a href="https://app.graphite.dev/github/pr/toeverything/blocksuite/7479?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#7475** <a href="https://app.graphite.dev/github/pr/toeverything/blocksuite/7475?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @fundon and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Flrande — APPROVED** [review]

**Review by Saul-Mirone — APPROVED** [review]

**Comment by fundon** [comment]
@Svaney-ssman https://github.com/toeverything/blocksuite/pull/7483#pullrequestreview-2158470702
The issues are fixed here.

**Comment by Svaney-ssman** [comment]
> @Svaney-ssman [#7483 (review)](https://github.com/toeverything/blocksuite/pull/7483#pullrequestreview-2158470702) The issues are fixed here.

Thanks, may you change the sequence to inline, card, embed?
CleanShot 2024-07-05 at 10 32 19@2x

**Comment by fundon** [comment]
> Thanks, may you change the sequence to inline, card, embed?

Updated. Please check again.

**Review by lawvs — APPROVED** [review]

**Review by Svaney-ssman — APPROVED** [review]

**Pull request merged**
