### PR TITLE
feat: affine packages

### PR DESCRIPTION
**Pull request by Saul-Mirone**
In this pr, we will aim to build structure as

```
|- packages
      |- affine
          |- model
          |- shared
              |- utils
              |- theme
          |- components
              |- rich-text
              |- remote-selection
          |- code-block
          |- list-block
          |- paragraph-block
```

And in `@blocksuite/blocks`, we install packages like `@blocksuite/affine-code-block`.

This pr introduces `@blocksuite/affine-model`, `@blocksuite/affine-shared` and `@blocksuite/affine-components`.

## `@blocksuite/affine-model`

The schema of the models provided to affine.

## `@blocksuite/affine-shared`

Common utils, constants and types

## `@blocksuite/affine-components`

Common components like `Icon`, `RichText`, `Toolbar`.

### CODE REVIEW

**Comment by Saul-Mirone** [comment]
* **#7852** <a href="https://app.graphite.dev/github/pr/toeverything/blocksuite/7852?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Saul-Mirone and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Flrande — APPROVED** [review]

**Comment by fourdim** [comment]
`typedoc.json` and `tsconfig.json` in the root dir should also be updated.

**Comment by Saul-Mirone** [comment]
> `typedoc.json`, `vitest.workspace.js` and `tsconfig.json` in the root dir should also be updated.

Thanks, updated `vitest.workspace.js` and `typedoc.json`. For `tsconfig.json`, I think we don't need to update it because it has a reference with `@blocksuite/blocks` which holds the references to the affine packages.

**Comment by akumatus** [comment]
Why not put `attachment-model.ts` file to `packages/blocks/src/attachment-block`? All logic about attachment should in one package

**Pull request merged**
