### PR TITLE
feat: hide title placeholder in ime

### PR DESCRIPTION
**Pull request by zqran**
before:
image

after:
image

### CODE REVIEW

**Review by lawvs — CHANGES_REQUESTED** [review]
The issue occurred because Lit was not updated in a timely manner. Perhaps a different approach should have been taken.

https://user-images.githubusercontent.com/18554747/222875463-fc2b1825-08d7-4430-b901-a83d490a0947.mov

**Comment by lawvs** [comment]
Also related to https://github.com/toeverything/blocksuite/issues/1258

**Comment by Flrande** [comment]
The placeholder just a pseudo-element from `:before` and you don't need to control meta data for it.

**Comment by zqran** [comment]
> The issue occurred because Lit was not updated in a timely manner. Perhaps a different approach should have been taken.

Yes, I also found out that the placeholder for the title disappears as soon as the mouse is moved

**Comment by zqran** [comment]
> The placeholder just a pseudo-element from `::before` and you don't need to control meta data for it.

I just want to trigger the title change in time and hide the placeholder, so that the UX is better

**Comment by zqran** [comment]
@lawvs Why do we need to re-render the block through mouse move?

**Comment by lawvs** [comment]
> @lawvs Why do we need to re-render the block through mouse move(mentioned in https://github.com/toeverything/blocksuite/issues/1258)?

It's just a bug

**Comment by zqran** [comment]
closed, see #1556

**Pull request closed without merging**
