### PR TITLE
fix: normal format should be inherited

### PR DESCRIPTION
**Pull request by lawvs**
Fix https://github.com/toeverything/blocksuite/issues/1818

### CODE REVIEW

**Comment by lawvs** [comment]
Could you check this implementation? @Flrande

**Review by Flrande — APPROVED** [review]

**Review by Flrande — CHANGES_REQUESTED** [review]
We should not inherited code and link style.

**Review by Flrande — APPROVED** [review]

**Comment by Flrande** [comment]
I will continue working on this branch.

**Comment by Flrande** [comment]
20230323103813_rec_

I think we should not inherited style here.

**Pull request closed without merging**
