### PR TITLE
fix(edgeless): edgeless portal does not render new added blocks

### PR DESCRIPTION
**Pull request by doouding**
Fixes [BS-685](https://linear.app/affine-design/issue/BS-685/edgeless-copy-paste-error)

### CODE REVIEW

**Comment by doouding** [comment]
* **#7440** <a href="https://app.graphite.dev/github/pr/toeverything/blocksuite/7440?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @doouding and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by Saul-Mirone** [comment]
Can we add a test case for this?

**Comment by L-Sun** [comment]
I feel that the code logic before and after the change is almost the same. What caused this bug? 🤔

**Comment by doouding** [comment]
> I feel that the code logic before and after the change is almost the same. What caused this bug? 🤔

I think lit cannot handle the `repeat` rendering in nested loop correctly. So I flat the array first.

**Comment by doouding** [comment]
> Can we add a test case for this?

Done.

**Review by Saul-Mirone — APPROVED** [review]

**Pull request merged**
