### PR TITLE
feat(edgeless): new TOC

### PR DESCRIPTION
**Pull request by donteatfriedrice**
New TOC:

https://www.figma.com/file/ry2HHWu5XafpuXBD2XOvKd/%F0%9F%9B%96-2023.S4?node-id=4435%3A113950&mode=dev

https://github.com/toeverything/blocksuite/assets/99816898/db1e2515-5e5d-4ad3-9912-fbada1a9862a

### CODE REVIEW

**Comment by zanwei** [comment]
Had a discussion with @donteatfriedrice internally. There are still some details that need to be fixed.

**Review by zanwei — APPROVED** [review]

**Comment by zanwei** [comment]
Approved. Looks good to me

**Review by doodlewind — APPROVED** [review]
Thanks for the feat!

**Comment by zanwei** [comment]
**We've further discussion about TOC and we like to have an update.**

1. Check whether the user has written content in the block. If there is no content, it will not be displayed in the TOC.
2. TOC when the text is not cut, it is necessary to click the corresponding block and jump to the target position. The corresponding block text is highlighted and returns to the default state after 1 second.
3. Placeholder block display type name

**UI update**
1. Please update the font size from 15px(base) to 14px(sm)
2. Please update the top&bot padding from 8px to 6px
3. Please update the indentation of different types of blocks

**Comment by donteatfriedrice** [comment]
Doc mode:

1. Display text outline.
2. Click to navigate to specific block.
3. Update outline in realtime.

https://github.com/toeverything/blocksuite/assets/99816898/78a26899-d350-4b9b-9f1a-136d76358acb

**Comment by donteatfriedrice** [comment]
Edgeless mode:

1. Support outline by note level.
2. Click to navigate to specific note.
3. Update panel in real-time.

https://github.com/toeverything/blocksuite/assets/99816898/39276d4a-e05f-4420-b868-4068ba772a9a

**Comment by donteatfriedrice** [comment]
Settings:

1. Support hiding block type icons.

https://github.com/toeverything/blocksuite/assets/99816898/e4b40202-ba06-4dfe-acf0-d80b86a18278

**Pull request merged**
