### PR TITLE
fix(blocks): redundant empty line in markdown list export

### LINKED ISSUE #6252: Redundant empty line between list item in copied markdown
When copying:

image

pasted result:

```
hello

* foo

* 123

* 123
```

expected:

```
hello
* foo
* 123
* 123
```

### PR DESCRIPTION
**Pull request by golok727**
image

# After
image

- This is the style in which Notion exports markdown lists

I don't know if this will fix #6252 or not because I am not able to copy it as a markdown

### CODE REVIEW

**Comment by fourdim** [comment]
I‘m sorry but it won't fix this issue because the issue is actually referring to:
When copying from BlockSuite and paste it to some websites (e.g. slack) (using html mime) will have an empty line between the list items.
In this case, there is no much difference whether you add a blank line or not. Most Markdown editor will interpret it as the same.
Thank you for your contribution and sorry for the ambiguity of this issue.

**Comment by golok727** [comment]
> I‘m sorry but it won't fix this issue because the issue is actually referring to: When copying from BlockSuite and paste it to some websites (e.g. slack) (using html mime) will have an empty line between the list items. In this case, there is no much difference whether you add a blank line or not. Most Markdown editor will interpret it as the same. Thank you for your contribution and sorry for the ambiguity of this issue.

How to reproduce this issue. When I copy and try to paste it is pasting as plain text with no empty lines and no bullets

**Comment by golok727** [comment]
> > I‘m sorry but it won't fix this issue because the issue is actually referring to: When copying from BlockSuite and paste it to some websites (e.g. slack) (using html mime) will have an empty line between the list items. In this case, there is no much difference whether you add a blank line or not. Most Markdown editor will interpret it as the same. Thank you for your contribution and sorry for the ambiguity of this issue.
> 
> It's ok! I actually intended to remove the empty line from the exported markdown as it was annoying me 😅 and my vs codes markdown renderer was giving extra spaces.. 
How to reproduce this issue? When I copy and try to paste, it is pasting as plain text with no empty lines and no bullets

**Comment by fourdim** [comment]
> > > I‘m sorry but it won't fix this issue because the issue is actually referring to: When copying from BlockSuite and paste it to some websites (e.g. slack) (using html mime) will have an empty line between the list items. In this case, there is no much difference whether you add a blank line or not. Most Markdown editor will interpret it as the same. Thank you for your contribution and sorry for the ambiguity of this issue.
> 
> It's ok! I actually intended to remove the empty line from the exported markdown as it was annoying me 😅 and my vs codes markdown renderer was giving extra spaces.. How to reproduce this issue? When I copy and try to paste, it is pasting as plain text with no empty lines and no bullets



> > I‘m sorry but it won't fix this issue because the issue is actually referring to: When copying from BlockSuite and paste it to some websites (e.g. slack) (using html mime) will have an empty line between the list items. In this case, there is no much difference whether you add a blank line or not. Most Markdown editor will interpret it as the same. Thank you for your contribution and sorry for the ambiguity of this issue.
> 
> How to reproduce this issue. When I copy and try to paste it is pasting as plain text with no empty lines and no bullets

Because you are pasting to the application that only accepts the `text/plain` mime.

You can see it in the https://evercoder.github.io/clipboard-inspector/.

In `text/html`, some application will interpret

```html
<div class="affine-block-children-container" style="padding-left: 26px;"></div>
```

as a new line.

**Comment by fourdim** [comment]
> > > I‘m sorry but it won't fix this issue because the issue is actually referring to: When copying from BlockSuite and paste it to some websites (e.g. slack) (using html mime) will have an empty line between the list items. In this case, there is no much difference whether you add a blank line or not. Most Markdown editor will interpret it as the same. Thank you for your contribution and sorry for the ambiguity of this issue.
> 
> It's ok! I actually intended to remove the empty line from the exported markdown as it was annoying me 😅 and my vs codes markdown renderer was giving extra spaces.. How to reproduce this issue? When I copy and try to paste, it is pasting as plain text with no empty lines and no bullets

I will fix it when transforming the AST.

**Pull request closed without merging**
