### PR TITLE
fix(page): image format bar overlaps import modal

### PR DESCRIPTION
**Pull request by RajeevDash007**
fixed: #4248 

https://github.com/toeverything/blocksuite/assets/96860040/9ccf4cc9-98b0-4426-ab9f-04ceaa705505

### CODE REVIEW

**Review by doodlewind — CHANGES_REQUESTED** [review]
https://www.codegram.com/blog/stop-ab-using-z-index/

**Comment by lawvs** [comment]
I believe we just need to add a simple `overlay mask` to prevent any hover operation in the editor.

**Comment by RajeevDash007** [comment]
> I believe we just need to add a simple `overlay mask` to prevent any hover operation in the editor.

 I guess, still we have to give the z-index value more than 1000 as most of the z-index are set to 1000

**Comment by lawvs** [comment]
> I guess, still we have to give the z-index value more than 1000 as most of the z-index are set to 1000

z-index only competes with sibling elements within the same [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context).

Screenshot 2023-08-24 at 14 29 36

**Review by lawvs — APPROVED** [review]

**Review by doodlewind — APPROVED** [review]

**Pull request merged**
