### PR TITLE
fix(page): updated UI of tooltips

### PR DESCRIPTION
**Pull request by RajeevDash007**
fixed: #4205 
Screenshot 2023-08-18 085255
Screenshot 2023-08-18 085231

If any more changes needed then please let me know

### CODE REVIEW

**Review by xell — CHANGES_REQUESTED** [review]
It seems the small triangle is missing in, for example, the tooltips of Block Hub:

CleanShot 2023-08-18 at 11 52 48@2x

Please check the [internal figma design](https://www.figma.com/file/UTTtfVCcStw1dKUg0gCSPo/%F0%9F%9B%9E-Design-System?type=design&node-id=441-5188&mode=design&t=IYnn1UiWplf0RvMt-4) to see the differences.

**Comment by RajeevDash007** [comment]
Screenshot 2023-08-18 100112
@xell as per the design, I changed the code to get this output.

**Comment by xell** [comment]
> Screenshot 2023-08-18 100112
> @xell as per the design, I changed the code to get this output.

It's not correct. The shape of the tooltip in every elements of the app should be:

img_v2_39f2ab03-6ac5-4393-ac60-811a4a000acg

**Review by xell — CHANGES_REQUESTED** [review]
Please consider to precisely implement the design in Figma.

**Comment by RajeevDash007** [comment]
Okay, I understood it wrong.
Now, it's clear. 
I will do it

**Comment by xell** [comment]
> Okay, I understood it wrong.
> Now, it's clear.
> I will do it

Thanks. And please consider the situation in Dark Mode as well.

**Review by xell — CHANGES_REQUESTED** [review]
You might need to consider the sub menu of Block Hub as well:

CleanShot 2023-08-21 at 16 22 00@2x

**Review by xell — APPROVED** [review]
LGTM

**Comment by RajeevDash007** [comment]
@doodlewind

**Review by doodlewind — APPROVED** [review]
Nice shot, thanks for polishing this!

**Pull request merged**
