### PR TITLE
fix: getPage maybe nullable

### PR DESCRIPTION
**Pull request by himself65**
upstream: 984ea012dec47f6dbe415aa7e875e9adb5cacae2

### CODE REVIEW

**Review by doodlewind — APPROVED** [review]
LGTM

**Comment by doodlewind** [comment]
`assertExists` can avoid the `foo!` warning

**Comment by himself65** [comment]
> `assertExists` can avoid the `foo!` warning

I use another workaround

**Comment by himself65** [comment]
> `assertExists` can avoid the `foo!` warning

Do you mean `assertExists` from '../packages/blocks'?

**Comment by doodlewind** [comment]
> Do you mean `assertExists` from '../packages/blocks'?

I think that may not work in a Node environment. But there are indeed some low-hanging fruits about our testing utils since we already intentionally have two `assertExists`. One is for browser runtime, and another is for unit testing the store (`test-utils-dom.ts`). Due to our complexity in testing (running tests across DOM and Node in a mixed way), it's challenging to decide the best practice to reuse test utils. I could chat later with you.

**Pull request merged**
