### PR TITLE
fix(blocks): missing aliases when duplicating linked doc block on edgeless

### PR DESCRIPTION
**Pull request by fundon**
Closes: [BS-2100](https://linear.app/affine-design/issue/BS-2100/在白板上，为添加了-alias-信息的-linked-doc-创建副本，会丢失-alias-信息)

### CODE REVIEW

**Comment by fundon** [comment]
* **#8930** <a href="https://app.graphite.dev/github/pr/toeverything/blocksuite/8930?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/toeverything/blocksuite/8930?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `master`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by L-Sun — COMMENTED** [review]
May `_createBookmarkBlock` need to be changed as well?

**Comment by fundon** [comment]
> May `_createBookmarkBlock` need to be changed as well?

let me check.

**Comment by L-Sun** [comment]
> > May `_createBookmarkBlock` need to be changed as well?
> 
> let me check.
> 
> Bookmark is an external link and does not require `pageId`.

Method `_createSyncedDocEmbedBlock` might also require 'referenceInfo'?

**Review by L-Sun — APPROVED** [review]
LGTM～

**Pull request merged**
