### PR TITLE
feat(edgeless): add overlay for note and shape tool

### PR DESCRIPTION
**Pull request by donteatfriedrice**
- [ ] Optimize edge cases

### CODE REVIEW

**Comment by regischen** [comment]
The positon of the overlay of the shape other than rect didn't overlap with the real shape when we click the mouse.
This may improve a little.

https://github.com/toeverything/blocksuite/assets/58546692/438c7439-fbcb-421f-8294-95f264c943ea

**Comment by regischen** [comment]
It would be great if the overlay's position of note is same with the real created note

**Comment by donteatfriedrice** [comment]
> The positon of the overlay of the shape other than rect didn't overlap with the real shape when we click the mouse. This may improve a little.
> 
>  Screen.Recording.2023-07-05.at.16.20.05.mov

I will improve this. Now I have a question, I should modify the overlay style to rough, how can I achieve this? Should I modify the Overlay abstract class , add a override render method with RoughCanvas for it? Then when I implement the draw method, use the Rough style?

**Comment by regischen** [comment]
> > The positon of the overlay of the shape other than rect didn't overlap with the real shape when we click the mouse. This may improve a little.
> > Screen.Recording.2023-07-05.at.16.20.05.mov
> 
> I will improve this. Now I have a question, I should modify the overlay style to rough, how can I achieve this? Should I modify the Overlay abstract class , add a override render method with RoughCanvas for it? Then when I implement the draw method, use the Rough style?

image
this will meet your expectation

**Comment by donteatfriedrice** [comment]
> > > The positon of the overlay of the shape other than rect didn't overlap with the real shape when we click the mouse. This may improve a little.
> > > Screen.Recording.2023-07-05.at.16.20.05.mov
> > 
> > 
> > I will improve this. Now I have a question, I should modify the overlay style to rough, how can I achieve this? Should I modify the Overlay abstract class , add a override render method with RoughCanvas for it? Then when I implement the draw method, use the Rough style?
> 
> image this will meet your expectation

Ok, I will try. Thanks!!!

**Review by doodlewind — APPROVED** [review]
Several quick feedback:

* Incorrect overlay position on panning edgeless viewport (see the recording).
* Besides dragging, clicking on canvas should also add new shape element.
* Using the `RoughCanvas` style overlay for shape will be better. Also, it may also be good for the shape overlay to inherit the last shape element style edited, so that we can keeping adding "blue shape with red fill color".
* Minor padding issue for the text overlay.

https://github.com/toeverything/blocksuite/assets/7312949/6983b8db-22dc-4989-8af9-3be771fae9b2

image

But the current implementation is already awesome, let's get this landed!

**Pull request merged**
