### PR TITLE
fix(docs): add missing that-clause

### PR DESCRIPTION
**Pull request by DataDaoDe**
Reading over the docs I found this tiny typo.

### CODE REVIEW

**Comment by DataDaoDe** [comment]
I signed the agreement in [DataDaoDe:patch-2](https://github.com/toeverything/blocksuite/pull/2096)

**Review by doodlewind — APPROVED** [review]
Good catch 😄

**Comment by doodlewind** [comment]
FYI, the BlockSuite documentation will be updated substantively in the coming days. I'm shipping pages covering more topics, hope you can stay tuned! For any content you'd like to know about, feel free to give your feedback.

**Comment by DataDaoDe** [comment]
Hey @doodlewind , thanks that sounds great with the docs. I'm getting acclimated to the source code still will definitely reach out with any questions :)

**Pull request merged**
