### PR TITLE
fix(blocks): use createRef instead of query

### PR DESCRIPTION
**Pull request by fundon**
Closes [BS-1263](https://linear.app/affine-design/issue/BS-1263/embed-模块的caption功能点击后无效)

### CODE REVIEW

**Comment by fundon** [comment]
* **#8062** <a href="https://app.graphite.dev/github/pr/toeverything/blocksuite/8062?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @fundon and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Saul-Mirone — APPROVED** [review]
LGTM

**Comment by fundon** [comment]
Maybe creates a ref that will be better

**Review by Saul-Mirone — APPROVED** [review]
LGTM

**Pull request merged**
