### PR TITLE
style: use declare global

### PR DESCRIPTION
**Pull request by AkaraChen**

### CODE REVIEW

**Comment by doodlewind** [comment]
Thanks for your willingness contributing to BlockSuite! We are very open to minor improvements, as along as it can be trivially justified. For any possible help, we'll try our best to reply on GitHub issues and discussions. Hope to see your next take!

**Review by himself65 — APPROVED** [review]

**Comment by AkaraChen** [comment]
> Thanks for your willingness contributing to BlockSuite! We are very open to minor improvements, as along as it can be trivially justified. For any possible help, we'll try our best to reply on GitHub issues and discussions. Hope to see your next take!

I just closed pr because I was not sure if the global type declaration would affect other packages, now I'm sure 😂

**Comment by himself65** [comment]
I think there is a way to declare a global env file into ts config

**Comment by himself65** [comment]
Thanks for the first contribution on blocksuite. I added some small changes, which split it into another file, making the `main.ts` clear.

Look forward to your great impact on open source projects

**Pull request merged**
