### PR TITLE
fix(page): display of toggle icon of `list-block`

### PR DESCRIPTION
**Pull request by zqran**
close: #4907

https://github.com/toeverything/blocksuite/assets/15389209/9a341a50-d631-4b48-9b35-a119577653eb

### CODE REVIEW

**Comment by lawvs** [comment]
When hovering over the parent, the Toggle icon for children should not be shown. However, I suppose that when hovering over the children, the parent's toggle icon should be shown.

@houjoe0829 What do you think?

**Review by doodlewind — APPROVED** [review]
Good catch!

**Comment by donteatfriedrice** [comment]
It seems that the toggle icon should be visible when hover on drag handle. See #3770.

https://github.com/toeverything/blocksuite/assets/99816898/f44bc935-1bdf-4b84-9ff7-5c102221327c

**Comment by zqran** [comment]
> It seems that the toggle icon should be visible when hover on drag handle. See #3770.
> 
>  Screen.Recording.2023-09-27.at.10.52.03.mov

@houjoe0829 In this case, should the child's icon be displayed?

**Comment by lawvs** [comment]
> > It seems that the toggle icon should be visible when hover on drag handle. See #3770.
> > Screen.Recording.2023-09-27.at.10.52.03.mov
> 
> @houjoe0829 In this case, should the child's icon be displayed?

@hwangdev97 believes that this is necessary https://github.com/toeverything/blocksuite/pull/3770#issuecomment-1717508924

**Review by lawvs — APPROVED** [review]
Great works!

**Pull request merged**
