### PR TITLE
feat(database): new date-picker component

### PR DESCRIPTION
**Pull request by CatsJuice**
A basic use case is added to **kanban**'s `Date` column input

- [x] Basic data-picker with year/month/date select
- [x] Web accessibility support
- [ ] ~~Wrap popup logic(use as menu conveniently)~~
- [ ] ~~Native input alternative~~

The 3rd & 4th is better to be discussed and implement separately.

### CODE REVIEW

**Comment by Svaney-ssman** [comment]
Date picker design upgraded: [check in figma](https://www.figma.com/file/UTTtfVCcStw1dKUg0gCSPo/%F0%9F%9B%9E-Design-System?type=design&node-id=9190-20752&mode=design&t=84lOvPVqiz5Mp4qG-4)
1. TODAY,  <, > button resized 
image
2. Year select added. click arrow will jump to the last/next decade
image
3. range select canceled 
@CatsJuice 
This also cc @JimmFly

**Comment by hwangdev97** [comment]
I think, this is a bug ?

https://github.com/toeverything/blocksuite/assets/24713927/689ecc79-f91b-4668-8b37-9b5e292c5f30

**Review by hwangdev97 — APPROVED** [review]

**Comment by hwangdev97** [comment]
I think the UX part is OK for now, but I need her to look at the specific UI size information again. @Svaney-ssman

**Comment by hwangdev97** [comment]
I communicated with @Svaney-ssman  , no problem

**Comment by CatsJuice** [comment]
@zzj3720 cc.

**Review by zzj3720 — APPROVED** [review]

**Pull request merged**
