### PR TITLE
feat: run store testing if package change

### LINKED ISSUE #402: Run `pnpm test:store` in CI
Currently, we only run the `pnpm test` and `pnpm build` on CI. The test cases in the store package are ignored. It would be better to run `pnpm test:store` on CI, which can be a standalone check to improve CI speed.

### PR DESCRIPTION
**Pull request by darkskygit**
fix #402

### CODE REVIEW

**Review by Himself65 — CHANGES_REQUESTED** [review]
Id like to run it in another yml file

**Comment by darkskygit** [comment]
> Id like to run it in another yml file

what is your concern? time or maintainability

**Comment by doodlewind** [comment]
Yes, I think having another YML entry can help make testing faster.

**Comment by darkskygit** [comment]
> Yes, I think having another YML entry can help make testing faster.

We only need to split jobs to let the test run in parallel. Writing the similar type of actions in the same yaml helps us maintain it easily.

Action config now renew to parallel run test.

**Review by doodlewind — APPROVED** [review]
LGTM

**Review by Himself65 — APPROVED** [review]

**Pull request merged**
