### PR TITLE
fix(embed): don't show image option menu on selecting

### PR DESCRIPTION
**Pull request by fundon**
https://user-images.githubusercontent.com/27926/227482051-af614b89-e0f4-410b-b679-dcd6bfa30043.mov

### CODE REVIEW

**Comment by fundon** [comment]
test later

**Comment by doodlewind** [comment]
@fundon looks like this PR is in stale state. Could you try if the original issue (not sure what it is) can still be reproduced in our current version? Let's see what we can do to help this landed!

**Comment by fundon** [comment]
> @fundon looks like this PR is in stale state. Could you try if the original issue (not sure what it is) can still be reproduced in our current version? Let's see what we can do to help this landed!

I've just added a video

**Review by doodlewind — APPROVED** [review]
Let's land this, thanks for your follow up!

**Pull request merged**
